#!/usr/bin/env python3
"""
CivicFix — D7 Historical Projects Ingestion Script
=================================================
Ingests canonical district historical capital works projects, execution costs, and timeline precedents from:
- Datasets_Backend/india/D7_Historical_Projects/CivicFix_India_D7_Historical_Projects.csv (7,860 rows)
- Datasets_Backend/jharkhand/D7_Historical_Projects/CivicFix_Jharkhand_D7_Historical_Projects.csv (240 rows)

Generates idempotent SQL seed statements for:
- public.district_historical_projects (8,100 records total: 7,860 INDIA_D7 + 240 JHARKHAND_D7)

Usage:
  python3 scripts/ingest_d7_historical_projects.py
"""

import os
import csv
import sys

JH_ALIAS_MAP = {
    "bokaro": "JH-D01",
    "chatra": "JH-D02",
    "deoghar": "JH-D03",
    "dhanbad": "JH-D04",
    "dumka": "JH-D05",
    "east singhbhum": "JH-D06",
    "garhwa": "JH-D07",
    "giridih": "JH-D08",
    "godda": "JH-D09",
    "gumla": "JH-D10",
    "hazaribagh": "JH-D11",
    "jamtara": "JH-D12",
    "khunti": "JH-D13",
    "koderma": "JH-D14",
    "latehar": "JH-D15",
    "lohardaga": "JH-D16",
    "pakur": "JH-D17",
    "palamu": "JH-D18",
    "ramgarh": "JH-D19",
    "ranchi": "JH-D20",
    "sahibganj": "JH-D21",
    "saraikela kharsawan": "JH-D22",
    "seraikela-kharsawan": "JH-D22",
    "simdega": "JH-D23",
    "west singhbhum": "JH-D24"
}

def sql_escape(val):
    if val is None or val == "":
        return "NULL"
    val_str = str(val).replace("'", "''")
    return f"'{val_str}'"

def sql_num(val):
    if val is None or str(val).strip() == "":
        return "NULL"
    try:
        f = float(val)
        return str(f) if "." in str(val) else str(int(f))
    except ValueError:
        return "NULL"

def main():
    india_csv = "Datasets_Backend/india/D7_Historical_Projects/CivicFix_India_D7_Historical_Projects.csv"
    jharkhand_csv = "Datasets_Backend/jharkhand/D7_Historical_Projects/CivicFix_Jharkhand_D7_Historical_Projects.csv"
    india_d1_csv = "Datasets_Backend/india/D1_Population/CivicFix_India_D1_Population.csv"
    output_sql = "scripts/seed_d7_historical_projects.sql"

    if not os.path.exists(india_csv):
        print(f"Error: {india_csv} not found!", file=sys.stderr)
        sys.exit(1)

    # Build canonical ID map for Jharkhand districts
    jh_name_to_canon_id = {}
    if os.path.exists(india_d1_csv):
        with open(india_d1_csv, mode="r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for r in reader:
                if r["state_name"].lower() == "jharkhand":
                    dname = r["district_name"].lower().strip()
                    if dname == "saraikela kharsawan":
                        dname = "seraikela-kharsawan"
                    jh_name_to_canon_id[dname] = r["district_id"]

    print(f"Reading {india_csv}...")
    india_records = []
    with open(india_csv, mode="r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for r in reader:
            india_records.append(r)

    print(f"Read {len(india_records)} India D7 records.")

    print(f"Reading {jharkhand_csv}...")
    jh_records = []
    if os.path.exists(jharkhand_csv):
        with open(jharkhand_csv, mode="r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for r in reader:
                jh_records.append(r)
        print(f"Read {len(jh_records)} Jharkhand D7 records.")

    sql_lines = [
        "-- CivicFix: Seed Script for Dataset D7 (District Historical Government Projects)",
        "-- Auto-generated by scripts/ingest_d7_historical_projects.py",
        "-- Idempotent via ON CONFLICT (project_id) DO UPDATE",
        "",
        "BEGIN;",
        "",
        "-- ==========================================================================",
        "-- 1. CANONICAL PAN-INDIA D7 HISTORICAL PROJECTS (7,860 Records — INDIA_D7)",
        "-- ==========================================================================",
        ""
    ]

    # 1. India D7 Inserts
    for r in india_records:
        proj_id = r["project_id"].strip()
        dist_id = r["district_id"].strip()
        dist_name = r["district_name"].strip()
        dept_code = r["department_id"].strip()
        dept_name = r["department_name"].strip()
        proj_sector = r["project_sector"].strip()
        proj_type = r["project_type"].strip()
        proj_name = f"{dist_name} {proj_type}"
        fy = r["financial_year"].strip()
        status = r["project_status"].strip()
        est_cost = sql_num(r.get("estimated_cost_crore"))
        app_cost = sql_num(r.get("approved_cost_crore"))
        act_cost = sql_num(r.get("actual_cost_crore"))
        p_dur = sql_num(r.get("project_duration_months"))
        act_dur = sql_num(r.get("actual_duration_months"))
        ben_pop = sql_num(r.get("estimated_beneficiary_population"))
        comp_pct = sql_num(r.get("completion_percentage"))
        cost_var = sql_num(r.get("cost_variance_percentage"))
        time_var = sql_num(r.get("time_variance_percentage"))
        budget_src = sql_escape(r.get("budget_source_type", "").strip())
        impl_mode = sql_escape(r.get("implementation_mode", "").strip())
        contractor = sql_escape(r.get("contractor_or_implementer_type", "").strip())
        maint_req = sql_escape(r.get("maintenance_requirement_level", "").strip())
        cost_per_ben = sql_num(r.get("historical_cost_per_beneficiary"))
        eff_score = sql_num(r.get("project_execution_efficiency_score"))

        sql_lines.append(
            f"INSERT INTO public.district_historical_projects ("
            f"project_id, district_id, planning_sector_code, planning_sector_name, "
            f"project_sector, project_type, project_name, financial_year, project_status, "
            f"estimated_cost_crore, approved_cost_crore, actual_cost_crore, "
            f"project_duration_months, actual_duration_months, estimated_beneficiary_population, "
            f"completion_percentage, cost_variance_percentage, time_variance_percentage, "
            f"budget_source_type, implementation_mode, contractor_or_implementer_type, "
            f"maintenance_requirement_level, historical_cost_per_beneficiary, "
            f"project_execution_efficiency_score, source_dataset, source_record_id, reconciled_at) "
            f"VALUES ("
            f"{sql_escape(proj_id)}, {sql_escape(dist_id)}, {sql_escape(dept_code)}, {sql_escape(dept_name)}, "
            f"{sql_escape(proj_sector)}, {sql_escape(proj_type)}, {sql_escape(proj_name)}, {sql_escape(fy)}, {sql_escape(status)}, "
            f"{est_cost}, {app_cost}, {act_cost}, "
            f"{p_dur}, {act_dur}, {ben_pop}, "
            f"{comp_pct}, {cost_var}, {time_var}, "
            f"{budget_src}, {impl_mode}, {contractor}, "
            f"{maint_req}, {cost_per_ben}, "
            f"{eff_score}, 'INDIA_D7', {sql_escape(proj_id)}, now()) "
            f"ON CONFLICT (project_id) DO UPDATE SET "
            f"district_id = EXCLUDED.district_id, "
            f"planning_sector_code = EXCLUDED.planning_sector_code, "
            f"planning_sector_name = EXCLUDED.planning_sector_name, "
            f"project_sector = EXCLUDED.project_sector, "
            f"project_type = EXCLUDED.project_type, "
            f"project_name = EXCLUDED.project_name, "
            f"financial_year = EXCLUDED.financial_year, "
            f"project_status = EXCLUDED.project_status, "
            f"estimated_cost_crore = EXCLUDED.estimated_cost_crore, "
            f"approved_cost_crore = EXCLUDED.approved_cost_crore, "
            f"actual_cost_crore = EXCLUDED.actual_cost_crore, "
            f"project_duration_months = EXCLUDED.project_duration_months, "
            f"actual_duration_months = EXCLUDED.actual_duration_months, "
            f"estimated_beneficiary_population = EXCLUDED.estimated_beneficiary_population, "
            f"completion_percentage = EXCLUDED.completion_percentage, "
            f"cost_variance_percentage = EXCLUDED.cost_variance_percentage, "
            f"time_variance_percentage = EXCLUDED.time_variance_percentage, "
            f"budget_source_type = EXCLUDED.budget_source_type, "
            f"implementation_mode = EXCLUDED.implementation_mode, "
            f"contractor_or_implementer_type = EXCLUDED.contractor_or_implementer_type, "
            f"maintenance_requirement_level = EXCLUDED.maintenance_requirement_level, "
            f"historical_cost_per_beneficiary = EXCLUDED.historical_cost_per_beneficiary, "
            f"project_execution_efficiency_score = EXCLUDED.project_execution_efficiency_score, "
            f"source_dataset = EXCLUDED.source_dataset, "
            f"source_record_id = EXCLUDED.source_record_id, "
            f"reconciled_at = now(), updated_at = now();"
        )

    # 2. Regional Jharkhand D7 Inserts (240 records)
    if jh_records:
        sql_lines.extend([
            "",
            "-- ==========================================================================",
            "-- 2. REGIONAL JHARKHAND D7 HISTORICAL PROJECTS (240 Records — JHARKHAND_D7)",
            "-- ==========================================================================",
            ""
        ])

        for r in jh_records:
            dname = r["district_name"].lower().strip()
            if dname == "saraikela kharsawan":
                dname = "seraikela-kharsawan"
            
            canon_dist_id = jh_name_to_canon_id.get(dname)
            if not canon_dist_id:
                print(f"Warning: Could not match Jharkhand district {dname} to canonical ID", file=sys.stderr)
                continue

            proj_id = r["project_id"].strip()
            orig_dist_id = r["district_id"].strip()
            dist_name = r["district_name"].strip()
            dept_code = r["department_id"].strip()
            dept_name = r["department_name"].strip()
            proj_sector = r["project_sector"].strip()
            proj_type = r["project_type"].strip()
            proj_name = f"{dist_name} {proj_type}"
            fy = r["financial_year"].strip()
            status = r["project_status"].strip()
            est_cost = sql_num(r.get("estimated_cost_crore"))
            app_cost = sql_num(r.get("approved_cost_crore"))
            act_cost = sql_num(r.get("actual_cost_crore"))
            p_dur = sql_num(r.get("project_duration_months"))
            act_dur = sql_num(r.get("actual_duration_months"))
            ben_pop = sql_num(r.get("estimated_beneficiary_population"))
            comp_pct = sql_num(r.get("completion_percentage"))
            cost_var = sql_num(r.get("cost_variance_percentage"))
            time_var = sql_num(r.get("time_variance_percentage"))
            budget_src = sql_escape(r.get("budget_source_type", "").strip())
            impl_mode = sql_escape(r.get("implementation_mode", "").strip())
            contractor = sql_escape(r.get("contractor_or_implementer_type", "").strip())
            maint_req = sql_escape(r.get("maintenance_requirement_level", "").strip())
            cost_per_ben = sql_num(r.get("historical_cost_per_beneficiary"))
            eff_score = sql_num(r.get("project_execution_efficiency_score"))

            sql_lines.append(
                f"INSERT INTO public.district_historical_projects ("
                f"project_id, district_id, planning_sector_code, planning_sector_name, "
                f"project_sector, project_type, project_name, financial_year, project_status, "
                f"estimated_cost_crore, approved_cost_crore, actual_cost_crore, "
                f"project_duration_months, actual_duration_months, estimated_beneficiary_population, "
                f"completion_percentage, cost_variance_percentage, time_variance_percentage, "
                f"budget_source_type, implementation_mode, contractor_or_implementer_type, "
                f"maintenance_requirement_level, historical_cost_per_beneficiary, "
                f"project_execution_efficiency_score, source_dataset, source_record_id, reconciled_at) "
                f"VALUES ("
                f"{sql_escape(proj_id)}, {sql_escape(canon_dist_id)}, {sql_escape(dept_code)}, {sql_escape(dept_name)}, "
                f"{sql_escape(proj_sector)}, {sql_escape(proj_type)}, {sql_escape(proj_name)}, {sql_escape(fy)}, {sql_escape(status)}, "
                f"{est_cost}, {app_cost}, {act_cost}, "
                f"{p_dur}, {act_dur}, {ben_pop}, "
                f"{comp_pct}, {cost_var}, {time_var}, "
                f"{budget_src}, {impl_mode}, {contractor}, "
                f"{maint_req}, {cost_per_ben}, "
                f"{eff_score}, 'JHARKHAND_D7', {sql_escape(proj_id)}, now()) "
                f"ON CONFLICT (project_id) DO UPDATE SET "
                f"district_id = EXCLUDED.district_id, "
                f"planning_sector_code = EXCLUDED.planning_sector_code, "
                f"planning_sector_name = EXCLUDED.planning_sector_name, "
                f"project_sector = EXCLUDED.project_sector, "
                f"project_type = EXCLUDED.project_type, "
                f"project_name = EXCLUDED.project_name, "
                f"financial_year = EXCLUDED.financial_year, "
                f"project_status = EXCLUDED.project_status, "
                f"estimated_cost_crore = EXCLUDED.estimated_cost_crore, "
                f"approved_cost_crore = EXCLUDED.approved_cost_crore, "
                f"actual_cost_crore = EXCLUDED.actual_cost_crore, "
                f"project_duration_months = EXCLUDED.project_duration_months, "
                f"actual_duration_months = EXCLUDED.actual_duration_months, "
                f"estimated_beneficiary_population = EXCLUDED.estimated_beneficiary_population, "
                f"completion_percentage = EXCLUDED.completion_percentage, "
                f"cost_variance_percentage = EXCLUDED.cost_variance_percentage, "
                f"time_variance_percentage = EXCLUDED.time_variance_percentage, "
                f"budget_source_type = EXCLUDED.budget_source_type, "
                f"implementation_mode = EXCLUDED.implementation_mode, "
                f"contractor_or_implementer_type = EXCLUDED.contractor_or_implementer_type, "
                f"maintenance_requirement_level = EXCLUDED.maintenance_requirement_level, "
                f"historical_cost_per_beneficiary = EXCLUDED.historical_cost_per_beneficiary, "
                f"project_execution_efficiency_score = EXCLUDED.project_execution_efficiency_score, "
                f"source_dataset = EXCLUDED.source_dataset, "
                f"source_record_id = EXCLUDED.source_record_id, "
                f"reconciled_at = now(), updated_at = now();"
            )

    sql_lines.extend(["", "COMMIT;", ""])

    with open(output_sql, mode="w", encoding="utf-8") as f:
        f.write("\n".join(sql_lines))

    print(f"\nGenerated {output_sql} successfully with {len(sql_lines)} lines.")
    print("D7 Historical Projects Ingestion SQL is 100% idempotent via ON CONFLICT (project_id).")

if __name__ == "__main__":
    main()
