#!/usr/bin/env python3
"""
CivicFix — D8 Development Requests Ingestion Script
==================================================
Ingests canonical district benchmark development requests from:
- Datasets_Backend/india/D8_CivicFix_Development_Requests/CivicFix_India_D8_CivicFix_Development_Requests.csv (15,720 rows)
- Datasets_Backend/jharkhand/D8_CivicFix_Development_Requests/CivicFix_Jharkhand_D8_CivicFix_Development_Requests.csv (480 rows)

Generates idempotent SQL seed statements for:
- public.benchmark_development_requests (16,200 records total: 15,720 INDIA_D8 + 480 JHARKHAND_D8)

Usage:
  python3 scripts/ingest_d8_development_requests.py
"""

import os
import csv
import sys

JH_ALIAS_MAP = {
    "bokaro": "JH-D01",
    "chatra": "JH-D02",
    "deoghar": "JH-D03",
    "dhanbad": "JH-D04",
    "dumka": "JH-D05",
    "east singhbhum": "JH-D06",
    "garhwa": "JH-D07",
    "giridih": "JH-D08",
    "godda": "JH-D09",
    "gumla": "JH-D10",
    "hazaribagh": "JH-D11",
    "jamtara": "JH-D12",
    "khunti": "JH-D13",
    "koderma": "JH-D14",
    "latehar": "JH-D15",
    "lohardaga": "JH-D16",
    "pakur": "JH-D17",
    "palamu": "JH-D18",
    "ramgarh": "JH-D19",
    "ranchi": "JH-D20",
    "sahibganj": "JH-D21",
    "saraikela kharsawan": "JH-D22",
    "seraikela-kharsawan": "JH-D22",
    "simdega": "JH-D23",
    "west singhbhum": "JH-D24"
}

def sql_escape(val):
    if val is None or val == "":
        return "NULL"
    val_str = str(val).replace("'", "''")
    return f"'{val_str}'"

def sql_num(val):
    if val is None or str(val).strip() == "":
        return "NULL"
    try:
        f = float(val)
        return str(f) if "." in str(val) else str(int(f))
    except ValueError:
        return "NULL"

def main():
    india_csv = "Datasets_Backend/india/D8_CivicFix_Development_Requests/CivicFix_India_D8_CivicFix_Development_Requests.csv"
    jharkhand_csv = "Datasets_Backend/jharkhand/D8_CivicFix_Development_Requests/CivicFix_Jharkhand_D8_CivicFix_Development_Requests.csv"
    india_d1_csv = "Datasets_Backend/india/D1_Population/CivicFix_India_D1_Population.csv"
    output_sql = "scripts/seed_d8_development_requests.sql"

    if not os.path.exists(india_csv):
        print(f"Error: {india_csv} not found!", file=sys.stderr)
        sys.exit(1)

    # Build canonical ID map for Jharkhand districts
    jh_name_to_canon_id = {}
    if os.path.exists(india_d1_csv):
        with open(india_d1_csv, mode="r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for r in reader:
                if r["state_name"].lower() == "jharkhand":
                    dname = r["district_name"].lower().strip()
                    if dname == "saraikela kharsawan":
                        dname = "seraikela-kharsawan"
                    jh_name_to_canon_id[dname] = r["district_id"]

    print(f"Reading {india_csv}...")
    india_records = []
    with open(india_csv, mode="r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for r in reader:
            india_records.append(r)

    print(f"Read {len(india_records)} India D8 records.")

    print(f"Reading {jharkhand_csv}...")
    jh_records = []
    if os.path.exists(jharkhand_csv):
        with open(jharkhand_csv, mode="r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for r in reader:
                jh_records.append(r)
        print(f"Read {len(jh_records)} Jharkhand D8 records.")

    sql_lines = [
        "-- CivicFix: Seed Script for Dataset D8 (Benchmark Development Requests)",
        "-- Auto-generated by scripts/ingest_d8_development_requests.py",
        "-- Idempotent via ON CONFLICT (benchmark_request_id) DO UPDATE",
        "",
        "BEGIN;",
        "",
        "-- ==========================================================================",
        "-- 1. CANONICAL PAN-INDIA D8 BENCHMARK REQUESTS (15,720 Records — INDIA_D8)",
        "-- ==========================================================================",
        ""
    ]

    # 1. India D8 Inserts
    for r in india_records:
        req_id = r["request_id"].strip()
        dist_id = r["district_id"].strip()
        cat = sql_escape(r.get("request_category", "").strip())
        req_type = sql_escape(r.get("request_type", "").strip())
        req_title = sql_escape(r.get("request_title", "").strip())
        req_desc = sql_escape(r.get("request_description", "").strip())
        dept_code = sql_escape(r.get("department_id", "").strip())
        cost = sql_num(r.get("estimated_project_cost_crore"))
        dur = sql_num(r.get("estimated_duration_months"))
        ben_pop = sql_num(r.get("estimated_beneficiary_population"))
        hh = sql_num(r.get("affected_households"))
        urgency = sql_escape(r.get("urgency_level", "").strip())
        serv_gap = sql_num(r.get("current_service_gap_score"))
        acc_gap = sql_num(r.get("accessibility_gap_score"))
        infra_gap = sql_num(r.get("infrastructure_gap_score"))
        socio_sc = sql_num(r.get("socioeconomic_context_score"))
        hist_cost = sql_num(r.get("historical_cost_context_crore"))
        avail_bud = sql_num(r.get("available_budget_context_crore"))
        press_sc = sql_num(r.get("budget_pressure_context_score"))
        ai_class = sql_escape(r.get("ai_complexity_classification", "").strip())
        conf = sql_num(r.get("ai_classification_confidence"))
        review_stat = sql_escape(r.get("admin_review_status", "").strip())
        reason = sql_escape(r.get("decision_reason_code", "").strip())

        sql_lines.append(
            f"INSERT INTO public.benchmark_development_requests ("
            f"benchmark_request_id, district_id, request_category, request_type, request_title, "
            f"request_description, planning_sector_code, estimated_project_cost_crore, estimated_duration_months, "
            f"estimated_beneficiary_population, affected_households, urgency_level, service_gap_score, "
            f"accessibility_gap_score, infrastructure_gap_score, socioeconomic_context_score, "
            f"historical_cost_context_crore, available_budget_context_crore, budget_pressure_context_score, "
            f"ai_complexity_classification, data_completeness_score, admin_review_status, decision_reason, "
            f"is_synthetic, source_dataset, source_record_id, reconciled_at) "
            f"VALUES ("
            f"{sql_escape(req_id)}, {sql_escape(dist_id)}, {cat}, {req_type}, {req_title}, "
            f"{req_desc}, {dept_code}, {cost}, {dur}, "
            f"{ben_pop}, {hh}, {urgency}, {serv_gap}, "
            f"{acc_gap}, {infra_gap}, {socio_sc}, "
            f"{hist_cost}, {avail_bud}, {press_sc}, "
            f"{ai_class}, {conf}, {review_stat}, {reason}, "
            f"true, 'INDIA_D8', {sql_escape(req_id)}, now()) "
            f"ON CONFLICT (benchmark_request_id) DO UPDATE SET "
            f"district_id = EXCLUDED.district_id, "
            f"request_category = EXCLUDED.request_category, "
            f"request_type = EXCLUDED.request_type, "
            f"request_title = EXCLUDED.request_title, "
            f"request_description = EXCLUDED.request_description, "
            f"planning_sector_code = EXCLUDED.planning_sector_code, "
            f"estimated_project_cost_crore = EXCLUDED.estimated_project_cost_crore, "
            f"estimated_duration_months = EXCLUDED.estimated_duration_months, "
            f"estimated_beneficiary_population = EXCLUDED.estimated_beneficiary_population, "
            f"affected_households = EXCLUDED.affected_households, "
            f"urgency_level = EXCLUDED.urgency_level, "
            f"service_gap_score = EXCLUDED.service_gap_score, "
            f"accessibility_gap_score = EXCLUDED.accessibility_gap_score, "
            f"infrastructure_gap_score = EXCLUDED.infrastructure_gap_score, "
            f"socioeconomic_context_score = EXCLUDED.socioeconomic_context_score, "
            f"historical_cost_context_crore = EXCLUDED.historical_cost_context_crore, "
            f"available_budget_context_crore = EXCLUDED.available_budget_context_crore, "
            f"budget_pressure_context_score = EXCLUDED.budget_pressure_context_score, "
            f"ai_complexity_classification = EXCLUDED.ai_complexity_classification, "
            f"data_completeness_score = EXCLUDED.data_completeness_score, "
            f"admin_review_status = EXCLUDED.admin_review_status, "
            f"decision_reason = EXCLUDED.decision_reason, "
            f"source_dataset = EXCLUDED.source_dataset, "
            f"source_record_id = EXCLUDED.source_record_id, "
            f"reconciled_at = now(), updated_at = now();"
        )

    # 2. Regional Jharkhand D8 Inserts (480 records)
    if jh_records:
        sql_lines.extend([
            "",
            "-- ==========================================================================",
            "-- 2. REGIONAL JHARKHAND D8 BENCHMARK REQUESTS (480 Records — JHARKHAND_D8)",
            "-- ==========================================================================",
            ""
        ])

        for r in jh_records:
            dname = r["district_name"].lower().strip()
            if dname == "saraikela kharsawan":
                dname = "seraikela-kharsawan"
            
            canon_dist_id = jh_name_to_canon_id.get(dname)
            if not canon_dist_id:
                print(f"Warning: Could not match Jharkhand district {dname} to canonical ID", file=sys.stderr)
                continue

            req_id = r["request_id"].strip()
            cat = sql_escape(r.get("request_category", "").strip())
            req_type = sql_escape(r.get("request_type", "").strip())
            req_title = sql_escape(r.get("request_title", "").strip())
            req_desc = sql_escape(r.get("request_description", "").strip())
            dept_code = sql_escape(r.get("department_id", "").strip())
            cost = sql_num(r.get("estimated_project_cost_crore"))
            dur = sql_num(r.get("estimated_duration_months"))
            ben_pop = sql_num(r.get("estimated_beneficiary_population"))
            hh = sql_num(r.get("affected_households"))
            urgency = sql_escape(r.get("urgency_level", "").strip())
            serv_gap = sql_num(r.get("current_service_gap_score"))
            acc_gap = sql_num(r.get("accessibility_gap_score"))
            infra_gap = sql_num(r.get("infrastructure_gap_score"))
            socio_sc = sql_num(r.get("socioeconomic_context_score"))
            hist_cost = sql_num(r.get("historical_cost_context_crore"))
            avail_bud = sql_num(r.get("available_budget_context_crore"))
            press_sc = sql_num(r.get("budget_pressure_context_score"))
            ai_class = sql_escape(r.get("ai_complexity_classification", "").strip())
            conf = sql_num(r.get("ai_classification_confidence"))
            review_stat = sql_escape(r.get("admin_review_status", "").strip())
            reason = sql_escape(r.get("decision_reason_code", "").strip())

            sql_lines.append(
                f"INSERT INTO public.benchmark_development_requests ("
                f"benchmark_request_id, district_id, request_category, request_type, request_title, "
                f"request_description, planning_sector_code, estimated_project_cost_crore, estimated_duration_months, "
                f"estimated_beneficiary_population, affected_households, urgency_level, service_gap_score, "
                f"accessibility_gap_score, infrastructure_gap_score, socioeconomic_context_score, "
                f"historical_cost_context_crore, available_budget_context_crore, budget_pressure_context_score, "
                f"ai_complexity_classification, data_completeness_score, admin_review_status, decision_reason, "
                f"is_synthetic, source_dataset, source_record_id, reconciled_at) "
                f"VALUES ("
                f"{sql_escape(req_id)}, {sql_escape(canon_dist_id)}, {cat}, {req_type}, {req_title}, "
                f"{req_desc}, {dept_code}, {cost}, {dur}, "
                f"{ben_pop}, {hh}, {urgency}, {serv_gap}, "
                f"{acc_gap}, {infra_gap}, {socio_sc}, "
                f"{hist_cost}, {avail_bud}, {press_sc}, "
                f"{ai_class}, {conf}, {review_stat}, {reason}, "
                f"true, 'JHARKHAND_D8', {sql_escape(req_id)}, now()) "
                f"ON CONFLICT (benchmark_request_id) DO UPDATE SET "
                f"district_id = EXCLUDED.district_id, "
                f"request_category = EXCLUDED.request_category, "
                f"request_type = EXCLUDED.request_type, "
                f"request_title = EXCLUDED.request_title, "
                f"request_description = EXCLUDED.request_description, "
                f"planning_sector_code = EXCLUDED.planning_sector_code, "
                f"estimated_project_cost_crore = EXCLUDED.estimated_project_cost_crore, "
                f"estimated_duration_months = EXCLUDED.estimated_duration_months, "
                f"estimated_beneficiary_population = EXCLUDED.estimated_beneficiary_population, "
                f"affected_households = EXCLUDED.affected_households, "
                f"urgency_level = EXCLUDED.urgency_level, "
                f"service_gap_score = EXCLUDED.service_gap_score, "
                f"accessibility_gap_score = EXCLUDED.accessibility_gap_score, "
                f"infrastructure_gap_score = EXCLUDED.infrastructure_gap_score, "
                f"socioeconomic_context_score = EXCLUDED.socioeconomic_context_score, "
                f"historical_cost_context_crore = EXCLUDED.historical_cost_context_crore, "
                f"available_budget_context_crore = EXCLUDED.available_budget_context_crore, "
                f"budget_pressure_context_score = EXCLUDED.budget_pressure_context_score, "
                f"ai_complexity_classification = EXCLUDED.ai_complexity_classification, "
                f"data_completeness_score = EXCLUDED.data_completeness_score, "
                f"admin_review_status = EXCLUDED.admin_review_status, "
                f"decision_reason = EXCLUDED.decision_reason, "
                f"source_dataset = EXCLUDED.source_dataset, "
                f"source_record_id = EXCLUDED.source_record_id, "
                f"reconciled_at = now(), updated_at = now();"
            )

    sql_lines.extend(["", "COMMIT;", ""])

    with open(output_sql, mode="w", encoding="utf-8") as f:
        f.write("\n".join(sql_lines))

    print(f"\nGenerated {output_sql} successfully with {len(sql_lines)} lines.")
    print("D8 Benchmark Requests Ingestion SQL is 100% idempotent via ON CONFLICT (benchmark_request_id).")

if __name__ == "__main__":
    main()
