#!/usr/bin/env python3
"""
CivicFix — D2 Budget & Fiscal Resources Ingestion Script (Source-Aware Provenance)
================================================================================
Ingests canonical district departmental budgets and financial resources from:
- Datasets_Backend/india/D2_Budget/CivicFix_India_D2_Budget.csv (23,580 rows)
- Datasets_Backend/jharkhand/D2_Budget/CivicFix_Jharkhand_D2_Budget.csv (720 rows)

Generates idempotent SQL seed statements for:
- public.district_department_budgets (24,300 records total: 23,580 INDIA_D2 + 720 JHARKHAND_D2)

Usage:
  python3 scripts/ingest_d2_budget.py
"""

import os
import csv
import sys

JH_ALIAS_MAP = {
    "bokaro": "JH-D01",
    "chatra": "JH-D02",
    "deoghar": "JH-D03",
    "dhanbad": "JH-D04",
    "dumka": "JH-D05",
    "east singhbhum": "JH-D06",
    "garhwa": "JH-D07",
    "giridih": "JH-D08",
    "godda": "JH-D09",
    "gumla": "JH-D10",
    "hazaribagh": "JH-D11",
    "jamtara": "JH-D12",
    "khunti": "JH-D13",
    "koderma": "JH-D14",
    "latehar": "JH-D15",
    "lohardaga": "JH-D16",
    "pakur": "JH-D17",
    "palamu": "JH-D18",
    "ramgarh": "JH-D19",
    "ranchi": "JH-D20",
    "sahibganj": "JH-D21",
    "saraikela kharsawan": "JH-D22",
    "seraikela-kharsawan": "JH-D22",
    "simdega": "JH-D23",
    "west singhbhum": "JH-D24"
}

def sql_escape(val):
    if val is None or val == "":
        return "NULL"
    val_str = str(val).replace("'", "''")
    return f"'{val_str}'"

def sql_num(val):
    if val is None or str(val).strip() == "":
        return "NULL"
    try:
        f = float(val)
        return str(f) if "." in str(val) else str(int(f))
    except ValueError:
        return "NULL"

def main():
    india_csv = "Datasets_Backend/india/D2_Budget/CivicFix_India_D2_Budget.csv"
    jharkhand_csv = "Datasets_Backend/jharkhand/D2_Budget/CivicFix_Jharkhand_D2_Budget.csv"
    india_d1_csv = "Datasets_Backend/india/D1_Population/CivicFix_India_D1_Population.csv"
    output_sql = "scripts/seed_d2_budget.sql"

    if not os.path.exists(india_csv):
        print(f"Error: {india_csv} not found!", file=sys.stderr)
        sys.exit(1)

    # Build canonical ID map for Jharkhand districts
    jh_name_to_canon_id = {}
    if os.path.exists(india_d1_csv):
        with open(india_d1_csv, mode="r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for r in reader:
                if r["state_name"].lower() == "jharkhand":
                    dname = r["district_name"].lower().strip()
                    if dname == "saraikela kharsawan":
                        dname = "seraikela-kharsawan"
                    jh_name_to_canon_id[dname] = r["district_id"]

    print(f"Reading {india_csv}...")
    india_records = []
    with open(india_csv, mode="r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for r in reader:
            india_records.append(r)

    print(f"Read {len(india_records)} India D2 records.")

    print(f"Reading {jharkhand_csv}...")
    jh_records = []
    if os.path.exists(jharkhand_csv):
        with open(jharkhand_csv, mode="r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for r in reader:
                jh_records.append(r)
        print(f"Read {len(jh_records)} Jharkhand D2 records.")

    sql_lines = [
        "-- CivicFix: Seed Script for Dataset D2 (District Departmental Budgets)",
        "-- Auto-generated by scripts/ingest_d2_budget.py",
        "-- Idempotent via ON CONFLICT (district_id, planning_sector_code, financial_year, funding_source, source_dataset) DO UPDATE",
        "",
        "BEGIN;",
        "",
        "-- ==========================================================================",
        "-- 1. CANONICAL PAN-INDIA D2 BUDGET ALLOCATIONS (23,580 Records — INDIA_D2)",
        "-- ==========================================================================",
        ""
    ]

    # 1. India D2 Inserts
    for r in india_records:
        fy = r["financial_year"].strip()
        dist_id = r["district_id"].strip()
        dept_code = r["department_id"].strip()
        dept_name = r["department_name"].strip()
        funding_source = "STATE"
        alloc = sql_num(r.get("allocated_budget_crore"))
        rel = sql_num(r.get("released_budget_crore"))
        comm = sql_num(r.get("committed_budget_crore"))
        spent = sql_num(r.get("spent_budget_crore"))
        unspent = sql_num(r.get("unspent_budget_crore"))
        avail = sql_num(r.get("available_for_new_development_crore"))
        util = sql_num(r.get("budget_utilization_percentage"))
        commit = sql_num(r.get("budget_commitment_percentage"))
        pressure = sql_num(r.get("budget_pressure_score"))
        source_rec_id = f"{dist_id}_{dept_code}_{fy}"

        sql_lines.append(
            f"INSERT INTO public.district_department_budgets ("
            f"district_id, planning_sector_code, planning_sector_name, financial_year, funding_source, "
            f"allocated_budget_crore, released_budget_crore, committed_budget_crore, spent_budget_crore, "
            f"unspent_budget_crore, available_for_new_development_crore, budget_utilization_percentage, "
            f"budget_commitment_percentage, budget_pressure_score, source_dataset, source_record_id, reconciled_at) "
            f"VALUES ("
            f"{sql_escape(dist_id)}, {sql_escape(dept_code)}, {sql_escape(dept_name)}, {sql_escape(fy)}, '{funding_source}', "
            f"{alloc}, {rel}, {comm}, {spent}, "
            f"{unspent}, {avail}, {util}, "
            f"{commit}, {pressure}, 'INDIA_D2', {sql_escape(source_rec_id)}, now()) "
            f"ON CONFLICT (district_id, planning_sector_code, financial_year, funding_source, source_dataset) DO UPDATE SET "
            f"planning_sector_name = EXCLUDED.planning_sector_name, "
            f"allocated_budget_crore = EXCLUDED.allocated_budget_crore, "
            f"released_budget_crore = EXCLUDED.released_budget_crore, "
            f"committed_budget_crore = EXCLUDED.committed_budget_crore, "
            f"spent_budget_crore = EXCLUDED.spent_budget_crore, "
            f"unspent_budget_crore = EXCLUDED.unspent_budget_crore, "
            f"available_for_new_development_crore = EXCLUDED.available_for_new_development_crore, "
            f"budget_utilization_percentage = EXCLUDED.budget_utilization_percentage, "
            f"budget_commitment_percentage = EXCLUDED.budget_commitment_percentage, "
            f"budget_pressure_score = EXCLUDED.budget_pressure_score, "
            f"source_record_id = EXCLUDED.source_record_id, "
            f"reconciled_at = now(), updated_at = now();"
        )

    # 2. Regional Jharkhand D2 Records (720 records — JHARKHAND_D2)
    if jh_records:
        sql_lines.extend([
            "",
            "-- ==========================================================================",
            "-- 2. REGIONAL JHARKHAND D2 BUDGET CALIBRATION (720 Records — JHARKHAND_D2)",
            "-- ==========================================================================",
            ""
        ])

        for r in jh_records:
            dname = r["district_name"].lower().strip()
            if dname == "saraikela kharsawan":
                dname = "seraikela-kharsawan"
            
            canon_dist_id = jh_name_to_canon_id.get(dname)
            if not canon_dist_id:
                print(f"Warning: Could not match Jharkhand district {dname} to canonical ID", file=sys.stderr)
                continue

            fy = r["financial_year"].strip()
            orig_dist_id = r["district_id"].strip()
            dept_code = r["department_id"].strip()
            dept_name = r["department_name"].strip()
            funding_source = "STATE"
            alloc = sql_num(r.get("allocated_budget_crore"))
            rel = sql_num(r.get("released_budget_crore"))
            comm = sql_num(r.get("committed_budget_crore"))
            spent = sql_num(r.get("spent_budget_crore"))
            unspent = sql_num(r.get("unspent_budget_crore"))
            avail = sql_num(r.get("available_for_new_development_crore"))
            util = sql_num(r.get("budget_utilization_percentage"))
            commit = sql_num(r.get("budget_commitment_percentage"))
            pressure = sql_num(r.get("budget_pressure_score"))
            source_rec_id = f"{orig_dist_id}_{dept_code}_{fy}"

            sql_lines.append(
                f"INSERT INTO public.district_department_budgets ("
                f"district_id, planning_sector_code, planning_sector_name, financial_year, funding_source, "
                f"allocated_budget_crore, released_budget_crore, committed_budget_crore, spent_budget_crore, "
                f"unspent_budget_crore, available_for_new_development_crore, budget_utilization_percentage, "
                f"budget_commitment_percentage, budget_pressure_score, source_dataset, source_record_id, reconciled_at) "
                f"VALUES ("
                f"{sql_escape(canon_dist_id)}, {sql_escape(dept_code)}, {sql_escape(dept_name)}, {sql_escape(fy)}, '{funding_source}', "
                f"{alloc}, {rel}, {comm}, {spent}, "
                f"{unspent}, {avail}, {util}, "
                f"{commit}, {pressure}, 'JHARKHAND_D2', {sql_escape(source_rec_id)}, now()) "
                f"ON CONFLICT (district_id, planning_sector_code, financial_year, funding_source, source_dataset) DO UPDATE SET "
                f"planning_sector_name = EXCLUDED.planning_sector_name, "
                f"allocated_budget_crore = EXCLUDED.allocated_budget_crore, "
                f"released_budget_crore = EXCLUDED.released_budget_crore, "
                f"committed_budget_crore = EXCLUDED.committed_budget_crore, "
                f"spent_budget_crore = EXCLUDED.spent_budget_crore, "
                f"unspent_budget_crore = EXCLUDED.unspent_budget_crore, "
                f"available_for_new_development_crore = EXCLUDED.available_for_new_development_crore, "
                f"budget_utilization_percentage = EXCLUDED.budget_utilization_percentage, "
                f"budget_commitment_percentage = EXCLUDED.budget_commitment_percentage, "
                f"budget_pressure_score = EXCLUDED.budget_pressure_score, "
                f"source_record_id = EXCLUDED.source_record_id, "
                f"reconciled_at = now(), updated_at = now();"
            )

    sql_lines.extend(["", "COMMIT;", ""])

    with open(output_sql, mode="w", encoding="utf-8") as f:
        f.write("\n".join(sql_lines))

    print(f"\nGenerated {output_sql} successfully with {len(sql_lines)} lines.")
    print("D2 Budget Ingestion SQL is 100% idempotent via ON CONFLICT (district_id, planning_sector_code, financial_year, funding_source, source_dataset).")

if __name__ == "__main__":
    main()
