#!/usr/bin/env python3
"""
CivicFix — D6 Socioeconomic & Service Gaps Ingestion Script
==========================================================
Ingests canonical district socioeconomic vulnerability, service deprivation, and development need indices from:
- Datasets_Backend/india/D6_Socioeconomic_Gaps/CivicFix_India_D6_Socioeconomic_Gaps.csv (786 rows)
- Datasets_Backend/jharkhand/D6_Socioeconomic_Gaps/CivicFix_Jharkhand_D6_Socioeconomic_Gaps.csv (24 rows)

Generates idempotent SQL seed statements for:
- public.district_socioeconomic_gaps (810 records total: 786 INDIA_D6 + 24 JHARKHAND_D6)

Usage:
  python3 scripts/ingest_d6_socioeconomic.py
"""

import os
import csv
import sys

JH_ALIAS_MAP = {
    "bokaro": "JH-D01",
    "chatra": "JH-D02",
    "deoghar": "JH-D03",
    "dhanbad": "JH-D04",
    "dumka": "JH-D05",
    "east singhbhum": "JH-D06",
    "garhwa": "JH-D07",
    "giridih": "JH-D08",
    "godda": "JH-D09",
    "gumla": "JH-D10",
    "hazaribagh": "JH-D11",
    "jamtara": "JH-D12",
    "khunti": "JH-D13",
    "koderma": "JH-D14",
    "latehar": "JH-D15",
    "lohardaga": "JH-D16",
    "pakur": "JH-D17",
    "palamu": "JH-D18",
    "ramgarh": "JH-D19",
    "ranchi": "JH-D20",
    "sahibganj": "JH-D21",
    "saraikela kharsawan": "JH-D22",
    "seraikela-kharsawan": "JH-D22",
    "simdega": "JH-D23",
    "west singhbhum": "JH-D24"
}

def sql_escape(val):
    if val is None or val == "":
        return "NULL"
    val_str = str(val).replace("'", "''")
    return f"'{val_str}'"

def sql_num(val):
    if val is None or str(val).strip() == "":
        return "NULL"
    try:
        f = float(val)
        return str(f) if "." in str(val) else str(int(f))
    except ValueError:
        return "NULL"

def main():
    india_csv = "Datasets_Backend/india/D6_Socioeconomic_Gaps/CivicFix_India_D6_Socioeconomic_Gaps.csv"
    jharkhand_csv = "Datasets_Backend/jharkhand/D6_Socioeconomic_Gaps/CivicFix_Jharkhand_D6_Socioeconomic_Gaps.csv"
    india_d1_csv = "Datasets_Backend/india/D1_Population/CivicFix_India_D1_Population.csv"
    output_sql = "scripts/seed_d6_socioeconomic.sql"

    if not os.path.exists(india_csv):
        print(f"Error: {india_csv} not found!", file=sys.stderr)
        sys.exit(1)

    # Build canonical ID map for Jharkhand districts
    jh_name_to_canon_id = {}
    if os.path.exists(india_d1_csv):
        with open(india_d1_csv, mode="r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for r in reader:
                if r["state_name"].lower() == "jharkhand":
                    dname = r["district_name"].lower().strip()
                    if dname == "saraikela kharsawan":
                        dname = "seraikela-kharsawan"
                    jh_name_to_canon_id[dname] = r["district_id"]

    print(f"Reading {india_csv}...")
    india_records = []
    with open(india_csv, mode="r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for r in reader:
            india_records.append(r)

    print(f"Read {len(india_records)} India D6 records.")

    print(f"Reading {jharkhand_csv}...")
    jh_records = []
    if os.path.exists(jharkhand_csv):
        with open(jharkhand_csv, mode="r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for r in reader:
                jh_records.append(r)
        print(f"Read {len(jh_records)} Jharkhand D6 records.")

    sql_lines = [
        "-- CivicFix: Seed Script for Dataset D6 (District Socioeconomic & Service Gaps)",
        "-- Auto-generated by scripts/ingest_d6_socioeconomic.py",
        "-- Idempotent via ON CONFLICT (district_id, source_dataset) DO UPDATE",
        "",
        "BEGIN;",
        "",
        "-- ==========================================================================",
        "-- 1. CANONICAL PAN-INDIA D6 SOCIOECONOMIC GAPS (786 Records — INDIA_D6)",
        "-- ==========================================================================",
        ""
    ]

    # 1. India D6 Inserts
    for r in india_records:
        dist_id = r["district_id"].strip()
        econ_v = sql_num(r.get("economic_vulnerability_score"))
        low_inc = sql_num(r.get("estimated_low_income_population_percentage"))
        emp_opp = sql_num(r.get("employment_opportunity_score"))
        econ_act = sql_num(r.get("economic_activity_score"))
        vuln_pop = sql_num(r.get("vulnerable_population_percentage"))
        health = sql_num(r.get("healthcare_service_gap_score"))
        edu = sql_num(r.get("education_service_gap_score"))
        water = sql_num(r.get("water_sanitation_service_gap_score"))
        elec = sql_num(r.get("electricity_service_gap_score"))
        dig = sql_num(r.get("digital_connectivity_gap_score"))
        ess = sql_num(r.get("essential_service_gap_score"))
        dev = sql_num(r.get("development_need_context_score"))
        depr = sql_num(r.get("service_deprivation_score"))
        press = sql_num(r.get("socioeconomic_pressure_score"))
        overall = sql_num(r.get("overall_development_context_score"))

        sql_lines.append(
            f"INSERT INTO public.district_socioeconomic_gaps ("
            f"district_id, economic_vulnerability_score, estimated_low_income_population_percentage, "
            f"employment_opportunity_score, economic_activity_score, vulnerable_population_percentage, "
            f"healthcare_service_gap_score, education_service_gap_score, water_sanitation_service_gap_score, "
            f"electricity_service_gap_score, digital_connectivity_gap_score, essential_service_gap_score, "
            f"development_need_context_score, service_deprivation_score, socioeconomic_pressure_score, "
            f"overall_development_context_score, source_dataset, source_record_id, reconciled_at) "
            f"VALUES ("
            f"{sql_escape(dist_id)}, {econ_v}, {low_inc}, "
            f"{emp_opp}, {econ_act}, {vuln_pop}, "
            f"{health}, {edu}, {water}, "
            f"{elec}, {dig}, {ess}, "
            f"{dev}, {depr}, {press}, "
            f"{overall}, 'INDIA_D6', {sql_escape(dist_id)}, now()) "
            f"ON CONFLICT (district_id, source_dataset) DO UPDATE SET "
            f"economic_vulnerability_score = EXCLUDED.economic_vulnerability_score, "
            f"estimated_low_income_population_percentage = EXCLUDED.estimated_low_income_population_percentage, "
            f"employment_opportunity_score = EXCLUDED.employment_opportunity_score, "
            f"economic_activity_score = EXCLUDED.economic_activity_score, "
            f"vulnerable_population_percentage = EXCLUDED.vulnerable_population_percentage, "
            f"healthcare_service_gap_score = EXCLUDED.healthcare_service_gap_score, "
            f"education_service_gap_score = EXCLUDED.education_service_gap_score, "
            f"water_sanitation_service_gap_score = EXCLUDED.water_sanitation_service_gap_score, "
            f"electricity_service_gap_score = EXCLUDED.electricity_service_gap_score, "
            f"digital_connectivity_gap_score = EXCLUDED.digital_connectivity_gap_score, "
            f"essential_service_gap_score = EXCLUDED.essential_service_gap_score, "
            f"development_need_context_score = EXCLUDED.development_need_context_score, "
            f"service_deprivation_score = EXCLUDED.service_deprivation_score, "
            f"socioeconomic_pressure_score = EXCLUDED.socioeconomic_pressure_score, "
            f"overall_development_context_score = EXCLUDED.overall_development_context_score, "
            f"reconciled_at = now(), updated_at = now();"
        )

    # 2. Regional Jharkhand D6 Inserts (24 records)
    if jh_records:
        sql_lines.extend([
            "",
            "-- ==========================================================================",
            "-- 2. REGIONAL JHARKHAND D6 SOCIOECONOMIC GAPS (24 Records — JHARKHAND_D6)",
            "-- ==========================================================================",
            ""
        ])

        for r in jh_records:
            dname = r["district_name"].lower().strip()
            if dname == "saraikela kharsawan":
                dname = "seraikela-kharsawan"
            
            canon_dist_id = jh_name_to_canon_id.get(dname)
            if not canon_dist_id:
                print(f"Warning: Could not match Jharkhand district {dname} to canonical ID", file=sys.stderr)
                continue

            orig_dist_id = r["district_id"].strip()
            econ_v = sql_num(r.get("economic_vulnerability_score"))
            low_inc = sql_num(r.get("estimated_low_income_population_percentage"))
            emp_opp = sql_num(r.get("employment_opportunity_score"))
            econ_act = sql_num(r.get("economic_activity_score"))
            vuln_pop = sql_num(r.get("vulnerable_population_percentage"))
            health = sql_num(r.get("healthcare_service_gap_score"))
            edu = sql_num(r.get("education_service_gap_score"))
            water = sql_num(r.get("water_sanitation_service_gap_score"))
            elec = sql_num(r.get("electricity_service_gap_score"))
            dig = sql_num(r.get("digital_connectivity_gap_score"))
            ess = sql_num(r.get("essential_service_gap_score"))
            dev = sql_num(r.get("development_need_context_score"))
            depr = sql_num(r.get("service_deprivation_score"))
            press = sql_num(r.get("socioeconomic_pressure_score"))
            overall = sql_num(r.get("overall_development_context_score"))

            sql_lines.append(
                f"INSERT INTO public.district_socioeconomic_gaps ("
                f"district_id, economic_vulnerability_score, estimated_low_income_population_percentage, "
                f"employment_opportunity_score, economic_activity_score, vulnerable_population_percentage, "
                f"healthcare_service_gap_score, education_service_gap_score, water_sanitation_service_gap_score, "
                f"electricity_service_gap_score, digital_connectivity_gap_score, essential_service_gap_score, "
                f"development_need_context_score, service_deprivation_score, socioeconomic_pressure_score, "
                f"overall_development_context_score, source_dataset, source_record_id, reconciled_at) "
                f"VALUES ("
                f"{sql_escape(canon_dist_id)}, {econ_v}, {low_inc}, "
                f"{emp_opp}, {econ_act}, {vuln_pop}, "
                f"{health}, {edu}, {water}, "
                f"{elec}, {dig}, {ess}, "
                f"{dev}, {depr}, {press}, "
                f"{overall}, 'JHARKHAND_D6', {sql_escape(orig_dist_id)}, now()) "
                f"ON CONFLICT (district_id, source_dataset) DO UPDATE SET "
                f"economic_vulnerability_score = EXCLUDED.economic_vulnerability_score, "
                f"estimated_low_income_population_percentage = EXCLUDED.estimated_low_income_population_percentage, "
                f"employment_opportunity_score = EXCLUDED.employment_opportunity_score, "
                f"economic_activity_score = EXCLUDED.economic_activity_score, "
                f"vulnerable_population_percentage = EXCLUDED.vulnerable_population_percentage, "
                f"healthcare_service_gap_score = EXCLUDED.healthcare_service_gap_score, "
                f"education_service_gap_score = EXCLUDED.education_service_gap_score, "
                f"water_sanitation_service_gap_score = EXCLUDED.water_sanitation_service_gap_score, "
                f"electricity_service_gap_score = EXCLUDED.electricity_service_gap_score, "
                f"digital_connectivity_gap_score = EXCLUDED.digital_connectivity_gap_score, "
                f"essential_service_gap_score = EXCLUDED.essential_service_gap_score, "
                f"development_need_context_score = EXCLUDED.development_need_context_score, "
                f"service_deprivation_score = EXCLUDED.service_deprivation_score, "
                f"socioeconomic_pressure_score = EXCLUDED.socioeconomic_pressure_score, "
                f"overall_development_context_score = EXCLUDED.overall_development_context_score, "
                f"reconciled_at = now(), updated_at = now();"
            )

    sql_lines.extend(["", "COMMIT;", ""])

    with open(output_sql, mode="w", encoding="utf-8") as f:
        f.write("\n".join(sql_lines))

    print(f"\nGenerated {output_sql} successfully with {len(sql_lines)} lines.")
    print("D6 Socioeconomic Ingestion SQL is 100% idempotent via ON CONFLICT (district_id, source_dataset).")

if __name__ == "__main__":
    main()
