#!/usr/bin/env python3
"""
CivicFix — D5 Accessibility & Connectivity Ingestion Script
==========================================================
Ingests canonical district accessibility, road connectivity, and transit access metrics from:
- Datasets_Backend/india/D5_Accessibility/CivicFix_India_D5_Accessibility.csv (786 rows)
- Datasets_Backend/jharkhand/D5_Accessibility/CivicFix_Jharkhand_D5_Accessibility.csv (24 rows)

Generates idempotent SQL seed statements for:
- public.district_accessibility_metrics (810 records total: 786 INDIA_D5 + 24 JHARKHAND_D5)

Usage:
  python3 scripts/ingest_d5_accessibility.py
"""

import os
import csv
import sys

JH_ALIAS_MAP = {
    "bokaro": "JH-D01",
    "chatra": "JH-D02",
    "deoghar": "JH-D03",
    "dhanbad": "JH-D04",
    "dumka": "JH-D05",
    "east singhbhum": "JH-D06",
    "garhwa": "JH-D07",
    "giridih": "JH-D08",
    "godda": "JH-D09",
    "gumla": "JH-D10",
    "hazaribagh": "JH-D11",
    "jamtara": "JH-D12",
    "khunti": "JH-D13",
    "koderma": "JH-D14",
    "latehar": "JH-D15",
    "lohardaga": "JH-D16",
    "pakur": "JH-D17",
    "palamu": "JH-D18",
    "ramgarh": "JH-D19",
    "ranchi": "JH-D20",
    "sahibganj": "JH-D21",
    "saraikela kharsawan": "JH-D22",
    "seraikela-kharsawan": "JH-D22",
    "simdega": "JH-D23",
    "west singhbhum": "JH-D24"
}

def sql_escape(val):
    if val is None or val == "":
        return "NULL"
    val_str = str(val).replace("'", "''")
    return f"'{val_str}'"

def sql_num(val):
    if val is None or str(val).strip() == "":
        return "NULL"
    try:
        f = float(val)
        return str(f) if "." in str(val) else str(int(f))
    except ValueError:
        return "NULL"

def main():
    india_csv = "Datasets_Backend/india/D5_Accessibility/CivicFix_India_D5_Accessibility.csv"
    jharkhand_csv = "Datasets_Backend/jharkhand/D5_Accessibility/CivicFix_Jharkhand_D5_Accessibility.csv"
    india_d1_csv = "Datasets_Backend/india/D1_Population/CivicFix_India_D1_Population.csv"
    output_sql = "scripts/seed_d5_accessibility.sql"

    if not os.path.exists(india_csv):
        print(f"Error: {india_csv} not found!", file=sys.stderr)
        sys.exit(1)

    # Build canonical ID map for Jharkhand districts
    jh_name_to_canon_id = {}
    if os.path.exists(india_d1_csv):
        with open(india_d1_csv, mode="r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for r in reader:
                if r["state_name"].lower() == "jharkhand":
                    dname = r["district_name"].lower().strip()
                    if dname == "saraikela kharsawan":
                        dname = "seraikela-kharsawan"
                    jh_name_to_canon_id[dname] = r["district_id"]

    print(f"Reading {india_csv}...")
    india_records = []
    with open(india_csv, mode="r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for r in reader:
            india_records.append(r)

    print(f"Read {len(india_records)} India D5 records.")

    print(f"Reading {jharkhand_csv}...")
    jh_records = []
    if os.path.exists(jharkhand_csv):
        with open(jharkhand_csv, mode="r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for r in reader:
                jh_records.append(r)
        print(f"Read {len(jh_records)} Jharkhand D5 records.")

    sql_lines = [
        "-- CivicFix: Seed Script for Dataset D5 (District Accessibility & Connectivity Metrics)",
        "-- Auto-generated by scripts/ingest_d5_accessibility.py",
        "-- Idempotent via ON CONFLICT (district_id, source_dataset) DO UPDATE",
        "",
        "BEGIN;",
        "",
        "-- ==========================================================================",
        "-- 1. CANONICAL PAN-INDIA D5 ACCESSIBILITY (786 Records — INDIA_D5)",
        "-- ==========================================================================",
        ""
    ]

    # 1. India D5 Inserts
    for r in india_records:
        dist_id = r["district_id"].strip()
        road = sql_num(r.get("road_connectivity_score"))
        paved = sql_num(r.get("paved_road_coverage_percentage"))
        all_w = sql_num(r.get("all_weather_access_percentage"))
        pub_t = sql_num(r.get("public_transport_connectivity_score"))
        ttime = sql_num(r.get("average_travel_time_to_key_services_minutes"))
        dist_km = sql_num(r.get("average_distance_to_major_service_center_km"))
        remote_pop = sql_num(r.get("remote_population_percentage"))
        serv_acc = sql_num(r.get("service_accessibility_score"))
        trans_gap = sql_num(r.get("transport_access_gap_score"))
        remote_gap = sql_num(r.get("remote_area_access_gap_score"))
        overall_gap = sql_num(r.get("overall_accessibility_gap_score"))

        sql_lines.append(
            f"INSERT INTO public.district_accessibility_metrics ("
            f"district_id, road_connectivity_score, paved_road_coverage_percentage, "
            f"all_weather_access_percentage, public_transport_connectivity_score, "
            f"average_travel_time_minutes, average_distance_to_service_center_km, "
            f"remote_population_percentage, service_accessibility_score, "
            f"transport_access_gap_score, remote_area_access_gap_score, overall_accessibility_gap_score, "
            f"source_dataset, source_record_id, reconciled_at) "
            f"VALUES ("
            f"{sql_escape(dist_id)}, {road}, {paved}, "
            f"{all_w}, {pub_t}, "
            f"{ttime}, {dist_km}, "
            f"{remote_pop}, {serv_acc}, "
            f"{trans_gap}, {remote_gap}, {overall_gap}, "
            f"'INDIA_D5', {sql_escape(dist_id)}, now()) "
            f"ON CONFLICT (district_id, source_dataset) DO UPDATE SET "
            f"road_connectivity_score = EXCLUDED.road_connectivity_score, "
            f"paved_road_coverage_percentage = EXCLUDED.paved_road_coverage_percentage, "
            f"all_weather_access_percentage = EXCLUDED.all_weather_access_percentage, "
            f"public_transport_connectivity_score = EXCLUDED.public_transport_connectivity_score, "
            f"average_travel_time_minutes = EXCLUDED.average_travel_time_minutes, "
            f"average_distance_to_service_center_km = EXCLUDED.average_distance_to_service_center_km, "
            f"remote_population_percentage = EXCLUDED.remote_population_percentage, "
            f"service_accessibility_score = EXCLUDED.service_accessibility_score, "
            f"transport_access_gap_score = EXCLUDED.transport_access_gap_score, "
            f"remote_area_access_gap_score = EXCLUDED.remote_area_access_gap_score, "
            f"overall_accessibility_gap_score = EXCLUDED.overall_accessibility_gap_score, "
            f"reconciled_at = now(), updated_at = now();"
        )

    # 2. Regional Jharkhand D5 Inserts (24 records)
    if jh_records:
        sql_lines.extend([
            "",
            "-- ==========================================================================",
            "-- 2. REGIONAL JHARKHAND D5 ACCESSIBILITY (24 Records — JHARKHAND_D5)",
            "-- ==========================================================================",
            ""
        ])

        for r in jh_records:
            dname = r["district_name"].lower().strip()
            if dname == "saraikela kharsawan":
                dname = "seraikela-kharsawan"
            
            canon_dist_id = jh_name_to_canon_id.get(dname)
            if not canon_dist_id:
                print(f"Warning: Could not match Jharkhand district {dname} to canonical ID", file=sys.stderr)
                continue

            orig_dist_id = r["district_id"].strip()
            road = sql_num(r.get("road_connectivity_score"))
            paved = sql_num(r.get("paved_road_coverage_percentage"))
            all_w = sql_num(r.get("all_weather_access_percentage"))
            pub_t = sql_num(r.get("public_transport_connectivity_score"))
            ttime = sql_num(r.get("average_travel_time_to_key_services_minutes"))
            dist_km = sql_num(r.get("average_distance_to_major_service_center_km"))
            remote_pop = sql_num(r.get("remote_population_percentage"))
            serv_acc = sql_num(r.get("service_accessibility_score"))
            trans_gap = sql_num(r.get("transport_access_gap_score"))
            remote_gap = sql_num(r.get("remote_area_access_gap_score"))
            overall_gap = sql_num(r.get("overall_accessibility_gap_score"))

            sql_lines.append(
                f"INSERT INTO public.district_accessibility_metrics ("
                f"district_id, road_connectivity_score, paved_road_coverage_percentage, "
                f"all_weather_access_percentage, public_transport_connectivity_score, "
                f"average_travel_time_minutes, average_distance_to_service_center_km, "
                f"remote_population_percentage, service_accessibility_score, "
                f"transport_access_gap_score, remote_area_access_gap_score, overall_accessibility_gap_score, "
                f"source_dataset, source_record_id, reconciled_at) "
                f"VALUES ("
                f"{sql_escape(canon_dist_id)}, {road}, {paved}, "
                f"{all_w}, {pub_t}, "
                f"{ttime}, {dist_km}, "
                f"{remote_pop}, {serv_acc}, "
                f"{trans_gap}, {remote_gap}, {overall_gap}, "
                f"'JHARKHAND_D5', {sql_escape(orig_dist_id)}, now()) "
                f"ON CONFLICT (district_id, source_dataset) DO UPDATE SET "
                f"road_connectivity_score = EXCLUDED.road_connectivity_score, "
                f"paved_road_coverage_percentage = EXCLUDED.paved_road_coverage_percentage, "
                f"all_weather_access_percentage = EXCLUDED.all_weather_access_percentage, "
                f"public_transport_connectivity_score = EXCLUDED.public_transport_connectivity_score, "
                f"average_travel_time_minutes = EXCLUDED.average_travel_time_minutes, "
                f"average_distance_to_service_center_km = EXCLUDED.average_distance_to_service_center_km, "
                f"remote_population_percentage = EXCLUDED.remote_population_percentage, "
                f"service_accessibility_score = EXCLUDED.service_accessibility_score, "
                f"transport_access_gap_score = EXCLUDED.transport_access_gap_score, "
                f"remote_area_access_gap_score = EXCLUDED.remote_area_access_gap_score, "
                f"overall_accessibility_gap_score = EXCLUDED.overall_accessibility_gap_score, "
                f"reconciled_at = now(), updated_at = now();"
            )

    sql_lines.extend(["", "COMMIT;", ""])

    with open(output_sql, mode="w", encoding="utf-8") as f:
        f.write("\n".join(sql_lines))

    print(f"\nGenerated {output_sql} successfully with {len(sql_lines)} lines.")
    print("D5 Accessibility Ingestion SQL is 100% idempotent via ON CONFLICT (district_id, source_dataset).")

if __name__ == "__main__":
    main()
