#!/usr/bin/env python3
"""
CivicFix — D4 Infrastructure Assets & Deficit Scores Ingestion Script
===================================================================
Ingests canonical district physical infrastructure inventories and deficit scores from:
- Datasets_Backend/india/D4_Infrastructure/CivicFix_India_D4_Infrastructure.csv (6,288 rows)
- Datasets_Backend/jharkhand/D4_Infrastructure/CivicFix_Jharkhand_D4_Infrastructure.csv (192 rows)

Generates idempotent SQL seed statements for:
- public.district_infrastructure_assets (6,480 records total: 6,288 INDIA_D4 + 192 JHARKHAND_D4)

Usage:
  python3 scripts/ingest_d4_infrastructure.py
"""

import os
import csv
import sys

JH_ALIAS_MAP = {
    "bokaro": "JH-D01",
    "chatra": "JH-D02",
    "deoghar": "JH-D03",
    "dhanbad": "JH-D04",
    "dumka": "JH-D05",
    "east singhbhum": "JH-D06",
    "garhwa": "JH-D07",
    "giridih": "JH-D08",
    "godda": "JH-D09",
    "gumla": "JH-D10",
    "hazaribagh": "JH-D11",
    "jamtara": "JH-D12",
    "khunti": "JH-D13",
    "koderma": "JH-D14",
    "latehar": "JH-D15",
    "lohardaga": "JH-D16",
    "pakur": "JH-D17",
    "palamu": "JH-D18",
    "ramgarh": "JH-D19",
    "ranchi": "JH-D20",
    "sahibganj": "JH-D21",
    "saraikela kharsawan": "JH-D22",
    "seraikela-kharsawan": "JH-D22",
    "simdega": "JH-D23",
    "west singhbhum": "JH-D24"
}

def sql_escape(val):
    if val is None or val == "":
        return "NULL"
    val_str = str(val).replace("'", "''")
    return f"'{val_str}'"

def sql_num(val):
    if val is None or str(val).strip() == "":
        return "NULL"
    try:
        f = float(val)
        return str(f) if "." in str(val) else str(int(f))
    except ValueError:
        return "NULL"

def main():
    india_csv = "Datasets_Backend/india/D4_Infrastructure/CivicFix_India_D4_Infrastructure.csv"
    jharkhand_csv = "Datasets_Backend/jharkhand/D4_Infrastructure/CivicFix_Jharkhand_D4_Infrastructure.csv"
    india_d1_csv = "Datasets_Backend/india/D1_Population/CivicFix_India_D1_Population.csv"
    output_sql = "scripts/seed_d4_infrastructure.sql"

    if not os.path.exists(india_csv):
        print(f"Error: {india_csv} not found!", file=sys.stderr)
        sys.exit(1)

    # Build canonical ID map for Jharkhand districts
    jh_name_to_canon_id = {}
    if os.path.exists(india_d1_csv):
        with open(india_d1_csv, mode="r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for r in reader:
                if r["state_name"].lower() == "jharkhand":
                    dname = r["district_name"].lower().strip()
                    if dname == "saraikela kharsawan":
                        dname = "seraikela-kharsawan"
                    jh_name_to_canon_id[dname] = r["district_id"]

    print(f"Reading {india_csv}...")
    india_records = []
    with open(india_csv, mode="r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for r in reader:
            india_records.append(r)

    print(f"Read {len(india_records)} India D4 records.")

    print(f"Reading {jharkhand_csv}...")
    jh_records = []
    if os.path.exists(jharkhand_csv):
        with open(jharkhand_csv, mode="r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for r in reader:
                jh_records.append(r)
        print(f"Read {len(jh_records)} Jharkhand D4 records.")

    sql_lines = [
        "-- CivicFix: Seed Script for Dataset D4 (District Infrastructure Assets & Deficits)",
        "-- Auto-generated by scripts/ingest_d4_infrastructure.py",
        "-- Idempotent via ON CONFLICT (district_id, infrastructure_id, source_dataset) DO UPDATE",
        "",
        "BEGIN;",
        "",
        "-- ==========================================================================",
        "-- 1. CANONICAL PAN-INDIA D4 INFRASTRUCTURE ASSETS (6,288 Records — INDIA_D4)",
        "-- ==========================================================================",
        ""
    ]

    # 1. India D4 Inserts
    for r in india_records:
        dist_id = r["district_id"].strip()
        infra_id = r["infrastructure_id"].strip()
        infra_cat = r["infrastructure_category"].strip()
        exist_cnt = sql_num(r.get("existing_asset_count"))
        func_cnt = sql_num(r.get("functional_asset_count"))
        tot_cap = sql_num(r.get("estimated_capacity"))
        curr_usage = sql_num(r.get("estimated_current_usage"))
        util_pct = sql_num(r.get("utilization_percentage"))
        cov_pct = sql_num(r.get("population_coverage_percentage"))
        cond_sc = sql_num(r.get("average_condition_score"))
        gap_sc = sql_num(r.get("infrastructure_gap_score"))
        add_cap = sql_escape(str(r.get("additional_capacity_needed", "")).strip())
        source_rec_id = f"{dist_id}_{infra_id}"

        sql_lines.append(
            f"INSERT INTO public.district_infrastructure_assets ("
            f"district_id, infrastructure_id, infrastructure_category, "
            f"existing_asset_count, functional_asset_count, total_capacity, "
            f"current_utilization, utilization_percentage, population_coverage_percentage, "
            f"average_condition_score, infrastructure_gap_score, additional_capacity_needed, "
            f"source_dataset, source_record_id, reconciled_at) "
            f"VALUES ("
            f"{sql_escape(dist_id)}, {sql_escape(infra_id)}, {sql_escape(infra_cat)}, "
            f"{exist_cnt}, {func_cnt}, {tot_cap}, "
            f"{curr_usage}, {util_pct}, {cov_pct}, "
            f"{cond_sc}, {gap_sc}, {add_cap}, "
            f"'INDIA_D4', {sql_escape(source_rec_id)}, now()) "
            f"ON CONFLICT (district_id, infrastructure_id, source_dataset) DO UPDATE SET "
            f"infrastructure_category = EXCLUDED.infrastructure_category, "
            f"existing_asset_count = EXCLUDED.existing_asset_count, "
            f"functional_asset_count = EXCLUDED.functional_asset_count, "
            f"total_capacity = EXCLUDED.total_capacity, "
            f"current_utilization = EXCLUDED.current_utilization, "
            f"utilization_percentage = EXCLUDED.utilization_percentage, "
            f"population_coverage_percentage = EXCLUDED.population_coverage_percentage, "
            f"average_condition_score = EXCLUDED.average_condition_score, "
            f"infrastructure_gap_score = EXCLUDED.infrastructure_gap_score, "
            f"additional_capacity_needed = EXCLUDED.additional_capacity_needed, "
            f"reconciled_at = now(), updated_at = now();"
        )

    # 2. Regional Jharkhand D4 Inserts (192 records)
    if jh_records:
        sql_lines.extend([
            "",
            "-- ==========================================================================",
            "-- 2. REGIONAL JHARKHAND D4 INFRASTRUCTURE ASSETS (192 Records — JHARKHAND_D4)",
            "-- ==========================================================================",
            ""
        ])

        for r in jh_records:
            dname = r["district_name"].lower().strip()
            if dname == "saraikela kharsawan":
                dname = "seraikela-kharsawan"
            
            canon_dist_id = jh_name_to_canon_id.get(dname)
            if not canon_dist_id:
                print(f"Warning: Could not match Jharkhand district {dname} to canonical ID", file=sys.stderr)
                continue

            orig_dist_id = r["district_id"].strip()
            infra_id = r["infrastructure_id"].strip()
            infra_cat = r["infrastructure_category"].strip()
            exist_cnt = sql_num(r.get("existing_asset_count"))
            func_cnt = sql_num(r.get("functional_asset_count"))
            tot_cap = sql_num(r.get("estimated_capacity"))
            curr_usage = sql_num(r.get("estimated_current_usage"))
            util_pct = sql_num(r.get("utilization_percentage"))
            cov_pct = sql_num(r.get("population_coverage_percentage"))
            cond_sc = sql_num(r.get("average_condition_score"))
            gap_sc = sql_num(r.get("infrastructure_gap_score"))
            add_cap = sql_escape(str(r.get("additional_capacity_needed", "")).strip())
            source_rec_id = f"{orig_dist_id}_{infra_id}"

            sql_lines.append(
                f"INSERT INTO public.district_infrastructure_assets ("
                f"district_id, infrastructure_id, infrastructure_category, "
                f"existing_asset_count, functional_asset_count, total_capacity, "
                f"current_utilization, utilization_percentage, population_coverage_percentage, "
                f"average_condition_score, infrastructure_gap_score, additional_capacity_needed, "
                f"source_dataset, source_record_id, reconciled_at) "
                f"VALUES ("
                f"{sql_escape(canon_dist_id)}, {sql_escape(infra_id)}, {sql_escape(infra_cat)}, "
                f"{exist_cnt}, {func_cnt}, {tot_cap}, "
                f"{curr_usage}, {util_pct}, {cov_pct}, "
                f"{cond_sc}, {gap_sc}, {add_cap}, "
                f"'JHARKHAND_D4', {sql_escape(source_rec_id)}, now()) "
                f"ON CONFLICT (district_id, infrastructure_id, source_dataset) DO UPDATE SET "
                f"infrastructure_category = EXCLUDED.infrastructure_category, "
                f"existing_asset_count = EXCLUDED.existing_asset_count, "
                f"functional_asset_count = EXCLUDED.functional_asset_count, "
                f"total_capacity = EXCLUDED.total_capacity, "
                f"current_utilization = EXCLUDED.current_utilization, "
                f"utilization_percentage = EXCLUDED.utilization_percentage, "
                f"population_coverage_percentage = EXCLUDED.population_coverage_percentage, "
                f"average_condition_score = EXCLUDED.average_condition_score, "
                f"infrastructure_gap_score = EXCLUDED.infrastructure_gap_score, "
                f"additional_capacity_needed = EXCLUDED.additional_capacity_needed, "
                f"reconciled_at = now(), updated_at = now();"
            )

    sql_lines.extend(["", "COMMIT;", ""])

    with open(output_sql, mode="w", encoding="utf-8") as f:
        f.write("\n".join(sql_lines))

    print(f"\nGenerated {output_sql} successfully with {len(sql_lines)} lines.")
    print("D4 Infrastructure Ingestion SQL is 100% idempotent via ON CONFLICT (district_id, infrastructure_id, source_dataset).")

if __name__ == "__main__":
    main()
