#!/usr/bin/env python3
"""
CivicFix — D3 Geography & Spatial Attributes Ingestion Script
============================================================
Ingests canonical district geographic characteristics, coordinates, and spatial baselines from:
- Datasets_Backend/india/D3_Geography/CivicFix_India_D3_Geography.csv (786 rows)
- Datasets_Backend/jharkhand/D3_Geography/CivicFix_Jharkhand_D3_Geography.csv (24 rows)

Generates idempotent SQL seed statements for:
- public.district_geography (810 records total: 786 INDIA_D3 + 24 JHARKHAND_D3)

Usage:
  python3 scripts/ingest_d3_geography.py
"""

import os
import csv
import sys

JH_ALIAS_MAP = {
    "bokaro": "JH-D01",
    "chatra": "JH-D02",
    "deoghar": "JH-D03",
    "dhanbad": "JH-D04",
    "dumka": "JH-D05",
    "east singhbhum": "JH-D06",
    "garhwa": "JH-D07",
    "giridih": "JH-D08",
    "godda": "JH-D09",
    "gumla": "JH-D10",
    "hazaribagh": "JH-D11",
    "jamtara": "JH-D12",
    "khunti": "JH-D13",
    "koderma": "JH-D14",
    "latehar": "JH-D15",
    "lohardaga": "JH-D16",
    "pakur": "JH-D17",
    "palamu": "JH-D18",
    "ramgarh": "JH-D19",
    "ranchi": "JH-D20",
    "sahibganj": "JH-D21",
    "saraikela kharsawan": "JH-D22",
    "seraikela-kharsawan": "JH-D22",
    "simdega": "JH-D23",
    "west singhbhum": "JH-D24"
}

def sql_escape(val):
    if val is None or val == "":
        return "NULL"
    val_str = str(val).replace("'", "''")
    return f"'{val_str}'"

def sql_num(val):
    if val is None or str(val).strip() == "":
        return "NULL"
    try:
        f = float(val)
        return str(f) if "." in str(val) else str(int(f))
    except ValueError:
        return "NULL"

def sql_array(items):
    if not items:
        return "ARRAY[]::text[]"
    escaped = [f"'{str(x).replace('\'', '\'\'')}'" for x in items if str(x).strip()]
    if not escaped:
        return "ARRAY[]::text[]"
    return f"ARRAY[{', '.join(escaped)}]::text[]"

def main():
    india_csv = "Datasets_Backend/india/D3_Geography/CivicFix_India_D3_Geography.csv"
    jharkhand_csv = "Datasets_Backend/jharkhand/D3_Geography/CivicFix_Jharkhand_D3_Geography.csv"
    india_d1_csv = "Datasets_Backend/india/D1_Population/CivicFix_India_D1_Population.csv"
    output_sql = "scripts/seed_d3_geography.sql"

    if not os.path.exists(india_csv):
        print(f"Error: {india_csv} not found!", file=sys.stderr)
        sys.exit(1)

    # Build canonical ID map for Jharkhand districts
    jh_name_to_canon_id = {}
    if os.path.exists(india_d1_csv):
        with open(india_d1_csv, mode="r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for r in reader:
                if r["state_name"].lower() == "jharkhand":
                    dname = r["district_name"].lower().strip()
                    if dname == "saraikela kharsawan":
                        dname = "seraikela-kharsawan"
                    jh_name_to_canon_id[dname] = r["district_id"]

    print(f"Reading {india_csv}...")
    india_records = []
    with open(india_csv, mode="r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for r in reader:
            india_records.append(r)

    print(f"Read {len(india_records)} India D3 records.")

    print(f"Reading {jharkhand_csv}...")
    jh_records = []
    if os.path.exists(jharkhand_csv):
        with open(jharkhand_csv, mode="r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for r in reader:
                jh_records.append(r)
        print(f"Read {len(jh_records)} Jharkhand D3 records.")

    sql_lines = [
        "-- CivicFix: Seed Script for Dataset D3 (District Geography & Spatial Attributes)",
        "-- Auto-generated by scripts/ingest_d3_geography.py",
        "-- Idempotent via ON CONFLICT (district_id, source_dataset) DO UPDATE",
        "",
        "BEGIN;",
        "",
        "-- ==========================================================================",
        "-- 1. CANONICAL PAN-INDIA D3 GEOGRAPHY (786 Records — INDIA_D3)",
        "-- ==========================================================================",
        ""
    ]

    # 1. India D3 Inserts
    for r in india_records:
        dist_id = r["district_id"].strip()
        area_sq_km = sql_num(r.get("district_area_sq_km"))
        lat = sql_num(r.get("latitude"))
        lon = sql_num(r.get("longitude"))
        ns_ext = sql_num(r.get("north_south_extent_km"))
        ew_ext = sql_num(r.get("east_west_extent_km"))
        geo_reg = sql_escape(r.get("geographic_region", "").strip())
        rur_urb = sql_escape(r.get("rural_urban_character", "").strip())
        terrain = sql_escape(r.get("terrain_type", "").strip())
        density_cat = sql_escape(r.get("population_density_category", "").strip())
        hq_type = sql_escape(r.get("district_headquarter_type", "").strip())
        
        raw_neighbors = [n.strip() for n in r.get("neighboring_districts", "").split(";") if n.strip()]
        neighbor_arr = sql_array(raw_neighbors)
        neighbor_cnt = sql_num(r.get("neighbor_count", len(raw_neighbors)))

        sql_lines.append(
            f"INSERT INTO public.district_geography ("
            f"district_id, area_sq_km, centroid_latitude, centroid_longitude, "
            f"north_south_extent_km, east_west_extent_km, geographic_region, "
            f"rural_urban_character, terrain_type, density_category, "
            f"district_headquarters, neighboring_districts, neighbor_count, "
            f"source_dataset, source_record_id, reconciled_at) "
            f"VALUES ("
            f"{sql_escape(dist_id)}, {area_sq_km}, {lat}, {lon}, "
            f"{ns_ext}, {ew_ext}, {geo_reg}, "
            f"{rur_urb}, {terrain}, {density_cat}, "
            f"{hq_type}, {neighbor_arr}, {neighbor_cnt}, "
            f"'INDIA_D3', {sql_escape(dist_id)}, now()) "
            f"ON CONFLICT (district_id, source_dataset) DO UPDATE SET "
            f"area_sq_km = EXCLUDED.area_sq_km, "
            f"centroid_latitude = EXCLUDED.centroid_latitude, "
            f"centroid_longitude = EXCLUDED.centroid_longitude, "
            f"north_south_extent_km = EXCLUDED.north_south_extent_km, "
            f"east_west_extent_km = EXCLUDED.east_west_extent_km, "
            f"geographic_region = EXCLUDED.geographic_region, "
            f"rural_urban_character = EXCLUDED.rural_urban_character, "
            f"terrain_type = EXCLUDED.terrain_type, "
            f"density_category = EXCLUDED.density_category, "
            f"district_headquarters = EXCLUDED.district_headquarters, "
            f"neighboring_districts = EXCLUDED.neighboring_districts, "
            f"neighbor_count = EXCLUDED.neighbor_count, "
            f"reconciled_at = now(), updated_at = now();"
        )

    # 2. Regional Jharkhand D3 Inserts (24 records)
    if jh_records:
        sql_lines.extend([
            "",
            "-- ==========================================================================",
            "-- 2. REGIONAL JHARKHAND D3 GEOGRAPHY (24 Records — JHARKHAND_D3)",
            "-- ==========================================================================",
            ""
        ])

        for r in jh_records:
            dname = r["district_name"].lower().strip()
            if dname == "saraikela kharsawan":
                dname = "seraikela-kharsawan"
            
            canon_dist_id = jh_name_to_canon_id.get(dname)
            if not canon_dist_id:
                print(f"Warning: Could not match Jharkhand district {dname} to canonical ID", file=sys.stderr)
                continue

            orig_dist_id = r["district_id"].strip()
            area_sq_km = sql_num(r.get("district_area_sq_km"))
            lat = sql_num(r.get("latitude"))
            lon = sql_num(r.get("longitude"))
            ns_ext = sql_num(r.get("north_south_extent_km"))
            ew_ext = sql_num(r.get("east_west_extent_km"))
            geo_reg = sql_escape(r.get("geographic_region", "").strip())
            rur_urb = sql_escape(r.get("rural_urban_character", "").strip())
            terrain = sql_escape(r.get("terrain_type", "").strip())
            density_cat = sql_escape(r.get("population_density_category", "").strip())
            hq_type = sql_escape(r.get("district_headquarter_type", "").strip())
            
            raw_neighbors = [n.strip() for n in r.get("neighboring_districts", "").split(";") if n.strip()]
            neighbor_arr = sql_array(raw_neighbors)
            neighbor_cnt = sql_num(r.get("neighbor_count", len(raw_neighbors)))

            sql_lines.append(
                f"INSERT INTO public.district_geography ("
                f"district_id, area_sq_km, centroid_latitude, centroid_longitude, "
                f"north_south_extent_km, east_west_extent_km, geographic_region, "
                f"rural_urban_character, terrain_type, density_category, "
                f"district_headquarters, neighboring_districts, neighbor_count, "
                f"source_dataset, source_record_id, reconciled_at) "
                f"VALUES ("
                f"{sql_escape(canon_dist_id)}, {area_sq_km}, {lat}, {lon}, "
                f"{ns_ext}, {ew_ext}, {geo_reg}, "
                f"{rur_urb}, {terrain}, {density_cat}, "
                f"{hq_type}, {neighbor_arr}, {neighbor_cnt}, "
                f"'JHARKHAND_D3', {sql_escape(orig_dist_id)}, now()) "
                f"ON CONFLICT (district_id, source_dataset) DO UPDATE SET "
                f"area_sq_km = EXCLUDED.area_sq_km, "
                f"centroid_latitude = EXCLUDED.centroid_latitude, "
                f"centroid_longitude = EXCLUDED.centroid_longitude, "
                f"north_south_extent_km = EXCLUDED.north_south_extent_km, "
                f"east_west_extent_km = EXCLUDED.east_west_extent_km, "
                f"geographic_region = EXCLUDED.geographic_region, "
                f"rural_urban_character = EXCLUDED.rural_urban_character, "
                f"terrain_type = EXCLUDED.terrain_type, "
                f"density_category = EXCLUDED.density_category, "
                f"district_headquarters = EXCLUDED.district_headquarters, "
                f"neighboring_districts = EXCLUDED.neighboring_districts, "
                f"neighbor_count = EXCLUDED.neighbor_count, "
                f"reconciled_at = now(), updated_at = now();"
            )

    sql_lines.extend(["", "COMMIT;", ""])

    with open(output_sql, mode="w", encoding="utf-8") as f:
        f.write("\n".join(sql_lines))

    print(f"\nGenerated {output_sql} successfully with {len(sql_lines)} lines.")
    print("D3 Geography Ingestion SQL is 100% idempotent via ON CONFLICT (district_id, source_dataset).")

if __name__ == "__main__":
    main()
