#!/usr/bin/env python3
"""
CivicFix — D1 Population & Demographics Ingestion Script
======================================================
Ingests canonical district identity and demographic baseline from:
- Datasets_Backend/india/D1_Population/CivicFix_India_D1_Population.csv
- Datasets_Backend/jharkhand/D1_Population/CivicFix_Jharkhand_D1_Population.csv

Generates idempotent SQL seed statements for:
1. public.districts (786 canonical Indian districts)
2. public.district_demographics (786 canonical demographic records + 24 regional records)

Usage:
  python3 scripts/ingest_d1_demographics.py
"""

import os
import csv
import sys

JH_ALIAS_MAP = {
    "bokaro": "JH-D01",
    "chatra": "JH-D02",
    "deoghar": "JH-D03",
    "dhanbad": "JH-D04",
    "dumka": "JH-D05",
    "east singhbhum": "JH-D06",
    "garhwa": "JH-D07",
    "giridih": "JH-D08",
    "godda": "JH-D09",
    "gumla": "JH-D10",
    "hazaribagh": "JH-D11",
    "jamtara": "JH-D12",
    "khunti": "JH-D13",
    "koderma": "JH-D14",
    "latehar": "JH-D15",
    "lohardaga": "JH-D16",
    "pakur": "JH-D17",
    "palamu": "JH-D18",
    "ramgarh": "JH-D19",
    "ranchi": "JH-D20",
    "sahibganj": "JH-D21",
    "saraikela kharsawan": "JH-D22",
    "seraikela-kharsawan": "JH-D22",
    "simdega": "JH-D23",
    "west singhbhum": "JH-D24"
}

def sql_escape(val):
    if val is None or val == "":
        return "NULL"
    val_str = str(val).replace("'", "''")
    return f"'{val_str}'"

def sql_num(val):
    if val is None or str(val).strip() == "":
        return "NULL"
    try:
        f = float(val)
        return str(f) if "." in str(val) else str(int(f))
    except ValueError:
        return "NULL"

def main():
    india_csv = "Datasets_Backend/india/D1_Population/CivicFix_India_D1_Population.csv"
    jharkhand_csv = "Datasets_Backend/jharkhand/D1_Population/CivicFix_Jharkhand_D1_Population.csv"
    output_sql = "scripts/seed_d1_demographics.sql"

    if not os.path.exists(india_csv):
        print(f"Error: {india_csv} not found!", file=sys.stderr)
        sys.exit(1)

    print(f"Reading {india_csv}...")
    india_records = []
    with open(india_csv, mode="r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for r in reader:
            india_records.append(r)

    print(f"Read {len(india_records)} India D1 records.")

    print(f"Reading {jharkhand_csv}...")
    jh_records = []
    if os.path.exists(jharkhand_csv):
        with open(jharkhand_csv, mode="r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for r in reader:
                jh_records.append(r)
        print(f"Read {len(jh_records)} Jharkhand D1 records.")

    sql_lines = [
        "-- CivicFix: Seed Script for Canonical Districts & D1 Demographics",
        "-- Auto-generated by scripts/ingest_d1_demographics.py",
        "-- Idempotent via ON CONFLICT DO UPDATE",
        "",
        "BEGIN;",
        "",
        "-- ==========================================================================",
        "-- 1. CANONICAL DISTRICTS MASTER (786 Unique Districts of India)",
        "-- ==========================================================================",
        ""
    ]

    # 1. Generate Districts Master Inserts
    for r in india_records:
        dist_id = r["district_id"].strip()
        state_id = r.get("state_id", "").strip() or None
        state_name = r["state_name"].strip()
        district_name = r["district_name"].strip()
        official_code = r.get("official_district_code", "").strip() or None
        
        # Check if Jharkhand alias applies
        norm_name = district_name.lower()
        alt_codes = "ARRAY[]::text[]"
        if state_name.lower() == "jharkhand" and norm_name in JH_ALIAS_MAP:
            jh_alias = JH_ALIAS_MAP[norm_name]
            alt_codes = f"ARRAY['{jh_alias}']::text[]"

        sql_lines.append(
            f"INSERT INTO public.districts (id, country_code, state_code, state_name, district_name, official_district_code, canonical_source, alternate_source_codes, is_active) "
            f"VALUES ({sql_escape(dist_id)}, 'IN', {sql_escape(state_id)}, {sql_escape(state_name)}, {sql_escape(district_name)}, {sql_escape(official_code)}, 'INDIA_D1_D3', {alt_codes}, true) "
            f"ON CONFLICT (id) DO UPDATE SET "
            f"state_name = EXCLUDED.state_name, district_name = EXCLUDED.district_name, official_district_code = EXCLUDED.official_district_code, alternate_source_codes = EXCLUDED.alternate_source_codes, updated_at = now();"
        )

    sql_lines.extend([
        "",
        "-- ==========================================================================",
        "-- 2. CANONICAL D1 POPULATION & DEMOGRAPHICS (786 National Baseline Records)",
        "-- ==========================================================================",
        ""
    ])

    for r in india_records:
        dist_id = r["district_id"].strip()
        tot_pop = sql_num(r.get("total_population"))
        male_pop = sql_num(r.get("male_population"))
        fem_pop = sql_num(r.get("female_population"))
        rur_pop = sql_num(r.get("rural_population"))
        urb_pop = sql_num(r.get("urban_population"))
        child_pop = sql_num(r.get("children_0_14"))
        work_pop = sql_num(r.get("working_age_population_15_59"))
        eld_pop = sql_num(r.get("elderly_population_60_plus"))
        tot_hh = sql_num(r.get("total_households"))
        avg_hh_sz = sql_num(r.get("average_household_size"))
        sc_pop = sql_num(r.get("sc_population"))
        st_pop = sql_num(r.get("st_population"))
        lit_pct = sql_num(r.get("literacy_rate_percentage"))
        work_pct = sql_num(r.get("worker_participation_rate_percentage"))
        elec_pct = sql_num(r.get("households_with_electricity_percentage"))
        water_pct = sql_num(r.get("households_with_piped_water_percentage"))
        toil_pct = sql_num(r.get("households_with_toilet_percentage"))
        health_sc = sql_num(r.get("healthcare_access_score"))
        edu_sc = sql_num(r.get("education_access_score"))
        wat_sc = sql_num(r.get("water_access_score"))
        elec_sc = sql_num(r.get("electricity_access_score"))
        gap_sc = sql_num(r.get("overall_service_gap_score"))
        dev_sc = sql_num(r.get("development_need_score"))
        pop_imp_sc = sql_num(r.get("population_impact_score"))

        sql_lines.append(
            f"INSERT INTO public.district_demographics (district_id, total_population, male_population, female_population, rural_population, urban_population, children_0_14, working_age_population_15_59, elderly_population_60_plus, total_households, average_household_size, sc_population, st_population, literacy_rate_percentage, worker_participation_rate_percentage, households_with_electricity_percentage, households_with_piped_water_percentage, households_with_toilet_percentage, healthcare_access_score, education_access_score, water_access_score, electricity_access_score, overall_service_gap_score, development_need_score, population_impact_score, source_dataset, source_record_id, reconciled_at) "
            f"VALUES ({sql_escape(dist_id)}, {tot_pop}, {male_pop}, {fem_pop}, {rur_pop}, {urb_pop}, {child_pop}, {work_pop}, {eld_pop}, {tot_hh}, {avg_hh_sz}, {sc_pop}, {st_pop}, {lit_pct}, {work_pct}, {elec_pct}, {water_pct}, {toil_pct}, {health_sc}, {edu_sc}, {wat_sc}, {elec_sc}, {gap_sc}, {dev_sc}, {pop_imp_sc}, 'INDIA_D1', {sql_escape(dist_id)}, now()) "
            f"ON CONFLICT (district_id, source_dataset) DO UPDATE SET "
            f"total_population = EXCLUDED.total_population, total_households = EXCLUDED.total_households, sc_population = EXCLUDED.sc_population, st_population = EXCLUDED.st_population, development_need_score = EXCLUDED.development_need_score, population_impact_score = EXCLUDED.population_impact_score, updated_at = now();"
        )

    # 3. Generate Regional Jharkhand Inserts (Source Provenance = JHARKHAND_D1)
    if jh_records:
        sql_lines.extend([
            "",
            "-- ==========================================================================",
            "-- 3. REGIONAL JHARKHAND D1 DEMOGRAPHICS (24 Regional Provenance Records)",
            "-- ==========================================================================",
            ""
        ])

        # Find canonical ID map for Jharkhand districts
        jh_name_to_canon_id = {}
        for r in india_records:
            if r["state_name"].lower() == "jharkhand":
                dname = r["district_name"].lower().strip()
                if dname == "saraikela kharsawan":
                    dname = "seraikela-kharsawan"
                jh_name_to_canon_id[dname] = r["district_id"]

        for r in jh_records:
            dname = r["district_name"].lower().strip()
            canon_dist_id = jh_name_to_canon_id.get(dname)
            if not canon_dist_id:
                print(f"Warning: Could not match Jharkhand district {dname} to canonical ID", file=sys.stderr)
                continue

            jh_orig_id = r["district_id"].strip()
            tot_pop = sql_num(r.get("total_population"))
            male_pop = sql_num(r.get("male_population"))
            fem_pop = sql_num(r.get("female_population"))
            rur_pop = sql_num(r.get("rural_population"))
            urb_pop = sql_num(r.get("urban_population"))
            child_pop = sql_num(r.get("children_0_14"))
            work_pop = sql_num(r.get("working_age_population_15_59"))
            eld_pop = sql_num(r.get("elderly_population_60_plus"))
            tot_hh = sql_num(r.get("total_households"))
            avg_hh_sz = sql_num(r.get("average_household_size"))
            sc_pop = sql_num(r.get("sc_population"))
            st_pop = sql_num(r.get("st_population"))
            lit_pct = sql_num(r.get("literacy_rate_percentage"))
            work_pct = sql_num(r.get("worker_participation_rate_percentage"))
            elec_pct = sql_num(r.get("households_with_electricity_percentage"))
            water_pct = sql_num(r.get("households_with_piped_water_percentage"))
            toil_pct = sql_num(r.get("households_with_toilet_percentage"))
            health_sc = sql_num(r.get("healthcare_access_score"))
            edu_sc = sql_num(r.get("education_access_score"))
            wat_sc = sql_num(r.get("water_access_score"))
            elec_sc = sql_num(r.get("electricity_access_score"))
            gap_sc = sql_num(r.get("overall_service_gap_score"))
            dev_sc = sql_num(r.get("development_need_score"))
            pop_imp_sc = sql_num(r.get("population_impact_score"))

            sql_lines.append(
                f"INSERT INTO public.district_demographics (district_id, total_population, male_population, female_population, rural_population, urban_population, children_0_14, working_age_population_15_59, elderly_population_60_plus, total_households, average_household_size, sc_population, st_population, literacy_rate_percentage, worker_participation_rate_percentage, households_with_electricity_percentage, households_with_piped_water_percentage, households_with_toilet_percentage, healthcare_access_score, education_access_score, water_access_score, electricity_access_score, overall_service_gap_score, development_need_score, population_impact_score, source_dataset, source_record_id, reconciled_at) "
                f"VALUES ({sql_escape(canon_dist_id)}, {tot_pop}, {male_pop}, {fem_pop}, {rur_pop}, {urb_pop}, {child_pop}, {work_pop}, {eld_pop}, {tot_hh}, {avg_hh_sz}, {sc_pop}, {st_pop}, {lit_pct}, {work_pct}, {elec_pct}, {water_pct}, {toil_pct}, {health_sc}, {edu_sc}, {wat_sc}, {elec_sc}, {gap_sc}, {dev_sc}, {pop_imp_sc}, 'JHARKHAND_D1', {sql_escape(jh_orig_id)}, now()) "
                f"ON CONFLICT (district_id, source_dataset) DO UPDATE SET "
                f"total_population = EXCLUDED.total_population, total_households = EXCLUDED.total_households, sc_population = EXCLUDED.sc_population, st_population = EXCLUDED.st_population, development_need_score = EXCLUDED.development_need_score, population_impact_score = EXCLUDED.population_impact_score, updated_at = now();"
            )

    sql_lines.extend(["", "COMMIT;", ""])

    with open(output_sql, mode="w", encoding="utf-8") as f:
        f.write("\n".join(sql_lines))

    print(f"\nGenerated {output_sql} successfully with {len(sql_lines)} lines.")
    print("Ingestion SQL is 100% idempotent via ON CONFLICT clauses.")

if __name__ == "__main__":
    main()
