-- ============================================================================
-- CivicFix Infrastructure Track: Migration 0064
-- India-Wide Canonical District Master Registry (786 Districts, 36 States & UTs)
-- ============================================================================
-- Description:
-- Populates the canonical public.districts master table with all 786 administrative
-- districts across all 28 States and 8 Union Territories of India.
--
-- Data Provenance:
-- - Source: Local Government Directory (LGD) / Census Administrative Delineations
-- - Coverage: 786 unique administrative districts across 36 States & Union Territories
-- - Preserves canonical Jharkhand IDs (IN-D0229 to IN-D0252) exactly.
--
-- Invariants & Security:
-- - Idempotent insertion using ON CONFLICT (id) DO UPDATE.
-- - No D1-D8 datasets or statistics inserted.
-- - Public/Anon RLS read policy preserved for citizen dropdown selection.
-- - SIMPLE and COMPLEX workflows remain unaffected.
-- ============================================================================

INSERT INTO public.districts (
  id,
  country_code,
  state_code,
  state_name,
  district_name,
  official_district_code,
  canonical_source,
  alternate_source_codes,
  is_active
) VALUES
  ('IN-D0001', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Alluri Sitharama Raju', '545', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0002', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Anakapalli', '546', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0003', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Ananthapuramu', '502', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0004', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Annamayya', '547', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0005', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Bapatla', '548', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0006', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Chittoor', '503', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0007', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Dr. B.R. Ambedkar Konaseema', '549', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0008', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'East Godavari', '505', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0009', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Eluru', '550', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0010', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Guntur', '506', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0011', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Kakinada', '551', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0012', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Krishna', '510', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0013', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Kurnool', '511', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0014', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Nandyal', '552', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0015', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'NTR', '553', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0016', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Palnadu', '554', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0017', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Parvathipuram Manyam', '555', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0018', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Prakasam', '517', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0019', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Sri Potti Sriramulu Nellore', '515', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0020', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Sri Sathya Sai', '556', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0021', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Srikakulam', '519', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0022', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Tirupati', '557', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0023', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Visakhapatnam', '520', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0024', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Vizianagaram', '521', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0025', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'West Godavari', '523', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0026', 'IN', 'IN-ST-01', 'Andhra Pradesh', 'Y.S.R. Kadapa', '504', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0027', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Anjaw', '234', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0028', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Changlang', '235', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0029', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Dibang Valley', '236', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0030', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'East Kameng', '237', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0031', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'East Siang', '238', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0032', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Itanagar Capital Complex', '718', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0033', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Kamle', '719', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0034', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Kra Daadi', '666', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0035', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Kurung Kumey', '239', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0036', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Lepa Rada', '720', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0037', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Lohit', '240', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0038', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Longding', '657', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0039', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Lower Dibang Valley', '241', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0040', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Lower Siang', '670', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0041', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Lower Subansiri', '242', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0042', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Namsai', '665', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0043', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Pakke Kessang', '721', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0044', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Papum Pare', '243', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0045', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Shi Yomi', '722', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0046', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Siang', '669', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0047', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Tawang', '244', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0048', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Tirap', '245', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0049', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Upper Dibang Valley', '723', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0050', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Upper Siang', '246', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0051', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'Upper Subansiri', '247', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0052', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'West Kameng', '248', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0053', 'IN', 'IN-ST-02', 'Arunachal Pradesh', 'West Siang', '249', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0054', 'IN', 'IN-ST-03', 'Assam', 'Bajali', '736', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0055', 'IN', 'IN-ST-03', 'Assam', 'Baksa', '283', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0056', 'IN', 'IN-ST-03', 'Assam', 'Barpeta', '284', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0057', 'IN', 'IN-ST-03', 'Assam', 'Biswanath', '678', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0058', 'IN', 'IN-ST-03', 'Assam', 'Bongaigaon', '285', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0059', 'IN', 'IN-ST-03', 'Assam', 'Cachar', '286', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0060', 'IN', 'IN-ST-03', 'Assam', 'Charaideo', '679', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0061', 'IN', 'IN-ST-03', 'Assam', 'Chirang', '287', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0062', 'IN', 'IN-ST-03', 'Assam', 'Darrang', '288', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0063', 'IN', 'IN-ST-03', 'Assam', 'Dhemaji', '289', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0064', 'IN', 'IN-ST-03', 'Assam', 'Dhubri', '290', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0065', 'IN', 'IN-ST-03', 'Assam', 'Dibrugarh', '291', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0066', 'IN', 'IN-ST-03', 'Assam', 'Dima Hasao', '299', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0067', 'IN', 'IN-ST-03', 'Assam', 'Goalpara', '292', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0068', 'IN', 'IN-ST-03', 'Assam', 'Golaghat', '293', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0069', 'IN', 'IN-ST-03', 'Assam', 'Hailakandi', '294', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0070', 'IN', 'IN-ST-03', 'Assam', 'Hojai', '680', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0071', 'IN', 'IN-ST-03', 'Assam', 'Jorhat', '295', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0072', 'IN', 'IN-ST-03', 'Assam', 'Kamrup', '296', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0073', 'IN', 'IN-ST-03', 'Assam', 'Kamrup Metropolitan', '297', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0074', 'IN', 'IN-ST-03', 'Assam', 'Karbi Anglong', '298', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0075', 'IN', 'IN-ST-03', 'Assam', 'Karimganj', '300', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0076', 'IN', 'IN-ST-03', 'Assam', 'Kokrajhar', '301', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0077', 'IN', 'IN-ST-03', 'Assam', 'Lakhimpur', '302', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0078', 'IN', 'IN-ST-03', 'Assam', 'Majuli', '681', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0079', 'IN', 'IN-ST-03', 'Assam', 'Morigaon', '303', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0080', 'IN', 'IN-ST-03', 'Assam', 'Nagaon', '304', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0081', 'IN', 'IN-ST-03', 'Assam', 'Nalbari', '305', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0082', 'IN', 'IN-ST-03', 'Assam', 'Sivasagar', '306', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0083', 'IN', 'IN-ST-03', 'Assam', 'Sonitpur', '307', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0084', 'IN', 'IN-ST-03', 'Assam', 'South Salmara-Mankachar', '682', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0085', 'IN', 'IN-ST-03', 'Assam', 'Tamulpur', '740', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0086', 'IN', 'IN-ST-03', 'Assam', 'Tinsukia', '308', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0087', 'IN', 'IN-ST-03', 'Assam', 'Udalguri', '309', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0088', 'IN', 'IN-ST-03', 'Assam', 'West Karbi Anglong', '683', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0089', 'IN', 'IN-ST-04', 'Bihar', 'Araria', '188', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0090', 'IN', 'IN-ST-04', 'Bihar', 'Arwal', '611', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0091', 'IN', 'IN-ST-04', 'Bihar', 'Aurangabad', '189', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0092', 'IN', 'IN-ST-04', 'Bihar', 'Banka', '190', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0093', 'IN', 'IN-ST-04', 'Bihar', 'Begusarai', '191', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0094', 'IN', 'IN-ST-04', 'Bihar', 'Bhagalpur', '192', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0095', 'IN', 'IN-ST-04', 'Bihar', 'Bhojpur', '193', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0096', 'IN', 'IN-ST-04', 'Bihar', 'Buxar', '194', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0097', 'IN', 'IN-ST-04', 'Bihar', 'Darbhanga', '195', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0098', 'IN', 'IN-ST-04', 'Bihar', 'East Champaran', '213', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0099', 'IN', 'IN-ST-04', 'Bihar', 'Gaya', '196', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0100', 'IN', 'IN-ST-04', 'Bihar', 'Gopalganj', '197', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0101', 'IN', 'IN-ST-04', 'Bihar', 'Jamui', '198', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0102', 'IN', 'IN-ST-04', 'Bihar', 'Jehanabad', '199', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0103', 'IN', 'IN-ST-04', 'Bihar', 'Kaimur', '200', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0104', 'IN', 'IN-ST-04', 'Bihar', 'Katihar', '201', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0105', 'IN', 'IN-ST-04', 'Bihar', 'Khagaria', '202', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0106', 'IN', 'IN-ST-04', 'Bihar', 'Kishanganj', '203', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0107', 'IN', 'IN-ST-04', 'Bihar', 'Lakhisarai', '204', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0108', 'IN', 'IN-ST-04', 'Bihar', 'Madhepura', '205', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0109', 'IN', 'IN-ST-04', 'Bihar', 'Madhubani', '206', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0110', 'IN', 'IN-ST-04', 'Bihar', 'Munger', '207', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0111', 'IN', 'IN-ST-04', 'Bihar', 'Muzaffarpur', '208', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0112', 'IN', 'IN-ST-04', 'Bihar', 'Nalanda', '209', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0113', 'IN', 'IN-ST-04', 'Bihar', 'Nawada', '210', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0114', 'IN', 'IN-ST-04', 'Bihar', 'Patna', '211', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0115', 'IN', 'IN-ST-04', 'Bihar', 'Purnia', '212', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0116', 'IN', 'IN-ST-04', 'Bihar', 'Rohtas', '214', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0117', 'IN', 'IN-ST-04', 'Bihar', 'Saharsa', '215', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0118', 'IN', 'IN-ST-04', 'Bihar', 'Samastipur', '216', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0119', 'IN', 'IN-ST-04', 'Bihar', 'Saran', '217', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0120', 'IN', 'IN-ST-04', 'Bihar', 'Sheikhpura', '218', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0121', 'IN', 'IN-ST-04', 'Bihar', 'Sheohar', '219', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0122', 'IN', 'IN-ST-04', 'Bihar', 'Sitamarhi', '220', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0123', 'IN', 'IN-ST-04', 'Bihar', 'Siwan', '221', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0124', 'IN', 'IN-ST-04', 'Bihar', 'Supaul', '222', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0125', 'IN', 'IN-ST-04', 'Bihar', 'Vaishali', '223', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0126', 'IN', 'IN-ST-04', 'Bihar', 'West Champaran', '224', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0127', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Balod', '646', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0128', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Baloda Bazar', '647', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0129', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Balrampur', '648', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0130', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Bastar', '373', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0131', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Bemetara', '649', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0132', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Bijapur', '636', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0133', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Bilaspur', '375', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0134', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Dantewada', '374', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0135', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Dhamtari', '376', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0136', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Durg', '377', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0137', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Gariaband', '650', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0138', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Gaurela-Pendra-Marwahi', '734', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0139', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Janjgir-Champa', '378', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0140', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Jashpur', '379', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0141', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Kabirdham', '380', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0142', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Kanker', '381', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0143', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Khairagarh-Chhuikhadan-Gandai', '743', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0144', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Kondagaon', '651', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0145', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Korba', '382', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0146', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Koriya', '383', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0147', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Mahasamund', '384', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0148', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Manendragarh-Chirmiri-Bharatpur', '744', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0149', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Mohla-Manpur-Ambagarh Chowki', '745', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0150', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Mungeli', '652', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0151', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Narayanpur', '637', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0152', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Raigarh', '385', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0153', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Raipur', '386', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0154', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Rajnandgaon', '387', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0155', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Sakti', '746', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0156', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Sarangarh-Bilaigarh', '747', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0157', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Sukma', '653', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0158', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Surajpur', '654', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0159', 'IN', 'IN-ST-05', 'Chhattisgarh', 'Surguja', '388', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0160', 'IN', 'IN-ST-06', 'Goa', 'North Goa', '558', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0161', 'IN', 'IN-ST-06', 'Goa', 'South Goa', '559', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0162', 'IN', 'IN-ST-07', 'Gujarat', 'Ahmedabad', '438', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0163', 'IN', 'IN-ST-07', 'Gujarat', 'Amreli', '439', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0164', 'IN', 'IN-ST-07', 'Gujarat', 'Anand', '440', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0165', 'IN', 'IN-ST-07', 'Gujarat', 'Aravalli', '660', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0166', 'IN', 'IN-ST-07', 'Gujarat', 'Banaskantha', '441', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0167', 'IN', 'IN-ST-07', 'Gujarat', 'Bharuch', '442', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0168', 'IN', 'IN-ST-07', 'Gujarat', 'Bhavnagar', '443', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0169', 'IN', 'IN-ST-07', 'Gujarat', 'Botad', '661', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0170', 'IN', 'IN-ST-07', 'Gujarat', 'Chhota Udaipur', '662', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0171', 'IN', 'IN-ST-07', 'Gujarat', 'Dahod', '444', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0172', 'IN', 'IN-ST-07', 'Gujarat', 'Dang', '445', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0173', 'IN', 'IN-ST-07', 'Gujarat', 'Devbhumi Dwarka', '663', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0174', 'IN', 'IN-ST-07', 'Gujarat', 'Gandhinagar', '446', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0175', 'IN', 'IN-ST-07', 'Gujarat', 'Gir Somnath', '664', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0176', 'IN', 'IN-ST-07', 'Gujarat', 'Jamnagar', '447', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0177', 'IN', 'IN-ST-07', 'Gujarat', 'Junagadh', '448', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0178', 'IN', 'IN-ST-07', 'Gujarat', 'Kheda', '449', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0179', 'IN', 'IN-ST-07', 'Gujarat', 'Kutch', '450', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0180', 'IN', 'IN-ST-07', 'Gujarat', 'Mahisagar', '667', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0181', 'IN', 'IN-ST-07', 'Gujarat', 'Mehsana', '451', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0182', 'IN', 'IN-ST-07', 'Gujarat', 'Morbi', '668', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0183', 'IN', 'IN-ST-07', 'Gujarat', 'Narmada', '452', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0184', 'IN', 'IN-ST-07', 'Gujarat', 'Navsari', '453', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0185', 'IN', 'IN-ST-07', 'Gujarat', 'Panchmahal', '454', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0186', 'IN', 'IN-ST-07', 'Gujarat', 'Patan', '455', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0187', 'IN', 'IN-ST-07', 'Gujarat', 'Porbandar', '456', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0188', 'IN', 'IN-ST-07', 'Gujarat', 'Rajkot', '457', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0189', 'IN', 'IN-ST-07', 'Gujarat', 'Sabarkantha', '458', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0190', 'IN', 'IN-ST-07', 'Gujarat', 'Surat', '459', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0191', 'IN', 'IN-ST-07', 'Gujarat', 'Surendranagar', '460', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0192', 'IN', 'IN-ST-07', 'Gujarat', 'Tapi', '625', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0193', 'IN', 'IN-ST-07', 'Gujarat', 'Vadodara', '461', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0194', 'IN', 'IN-ST-07', 'Gujarat', 'Valsad', '462', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0195', 'IN', 'IN-ST-08', 'Haryana', 'Ambala', '57', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0196', 'IN', 'IN-ST-08', 'Haryana', 'Bhiwani', '58', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0197', 'IN', 'IN-ST-08', 'Haryana', 'Charkhi Dadri', '705', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0198', 'IN', 'IN-ST-08', 'Haryana', 'Faridabad', '59', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0199', 'IN', 'IN-ST-08', 'Haryana', 'Fatehabad', '60', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0200', 'IN', 'IN-ST-08', 'Haryana', 'Gurugram', '61', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0201', 'IN', 'IN-ST-08', 'Haryana', 'Hisar', '62', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0202', 'IN', 'IN-ST-08', 'Haryana', 'Jhajjar', '63', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0203', 'IN', 'IN-ST-08', 'Haryana', 'Jind', '64', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0204', 'IN', 'IN-ST-08', 'Haryana', 'Kaithal', '65', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0205', 'IN', 'IN-ST-08', 'Haryana', 'Karnal', '66', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0206', 'IN', 'IN-ST-08', 'Haryana', 'Kurukshetra', '67', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0207', 'IN', 'IN-ST-08', 'Haryana', 'Mahendragarh', '68', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0208', 'IN', 'IN-ST-08', 'Haryana', 'Nuh', '627', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0209', 'IN', 'IN-ST-08', 'Haryana', 'Palwal', '638', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0210', 'IN', 'IN-ST-08', 'Haryana', 'Panchkula', '69', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0211', 'IN', 'IN-ST-08', 'Haryana', 'Panipat', '70', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0212', 'IN', 'IN-ST-08', 'Haryana', 'Rewari', '71', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0213', 'IN', 'IN-ST-08', 'Haryana', 'Rohtak', '72', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0214', 'IN', 'IN-ST-08', 'Haryana', 'Sirsa', '73', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0215', 'IN', 'IN-ST-08', 'Haryana', 'Sonipat', '74', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0216', 'IN', 'IN-ST-08', 'Haryana', 'Yamunanagar', '75', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0217', 'IN', 'IN-ST-09', 'Himachal Pradesh', 'Bilaspur', '16', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0218', 'IN', 'IN-ST-09', 'Himachal Pradesh', 'Chamba', '17', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0219', 'IN', 'IN-ST-09', 'Himachal Pradesh', 'Hamirpur', '18', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0220', 'IN', 'IN-ST-09', 'Himachal Pradesh', 'Kangra', '19', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0221', 'IN', 'IN-ST-09', 'Himachal Pradesh', 'Kinnaur', '20', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0222', 'IN', 'IN-ST-09', 'Himachal Pradesh', 'Kullu', '21', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0223', 'IN', 'IN-ST-09', 'Himachal Pradesh', 'Lahaul and Spiti', '22', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0224', 'IN', 'IN-ST-09', 'Himachal Pradesh', 'Mandi', '23', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0225', 'IN', 'IN-ST-09', 'Himachal Pradesh', 'Shimla', '24', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0226', 'IN', 'IN-ST-09', 'Himachal Pradesh', 'Sirmaur', '25', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0227', 'IN', 'IN-ST-09', 'Himachal Pradesh', 'Solan', '26', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0228', 'IN', 'IN-ST-09', 'Himachal Pradesh', 'Una', '27', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0229', 'IN', 'IN-ST-10', 'Jharkhand', 'Bokaro', '315', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D01']::text[], true),
  ('IN-D0230', 'IN', 'IN-ST-10', 'Jharkhand', 'Chatra', '316', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D02']::text[], true),
  ('IN-D0231', 'IN', 'IN-ST-10', 'Jharkhand', 'Deoghar', '317', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D03']::text[], true),
  ('IN-D0232', 'IN', 'IN-ST-10', 'Jharkhand', 'Dhanbad', '318', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D04']::text[], true),
  ('IN-D0233', 'IN', 'IN-ST-10', 'Jharkhand', 'Dumka', '319', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D05']::text[], true),
  ('IN-D0234', 'IN', 'IN-ST-10', 'Jharkhand', 'East Singhbhum', '320', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D06']::text[], true),
  ('IN-D0235', 'IN', 'IN-ST-10', 'Jharkhand', 'Garhwa', '321', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D07']::text[], true),
  ('IN-D0236', 'IN', 'IN-ST-10', 'Jharkhand', 'Giridih', '322', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D08']::text[], true),
  ('IN-D0237', 'IN', 'IN-ST-10', 'Jharkhand', 'Godda', '323', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D09']::text[], true),
  ('IN-D0238', 'IN', 'IN-ST-10', 'Jharkhand', 'Gumla', '324', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D10']::text[], true),
  ('IN-D0239', 'IN', 'IN-ST-10', 'Jharkhand', 'Hazaribagh', '325', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D11']::text[], true),
  ('IN-D0240', 'IN', 'IN-ST-10', 'Jharkhand', 'Jamtara', '607', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D12']::text[], true),
  ('IN-D0241', 'IN', 'IN-ST-10', 'Jharkhand', 'Khunti', '629', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D13']::text[], true),
  ('IN-D0242', 'IN', 'IN-ST-10', 'Jharkhand', 'Koderma', '326', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D14']::text[], true),
  ('IN-D0243', 'IN', 'IN-ST-10', 'Jharkhand', 'Latehar', '608', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D15']::text[], true),
  ('IN-D0244', 'IN', 'IN-ST-10', 'Jharkhand', 'Lohardaga', '327', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D16']::text[], true),
  ('IN-D0245', 'IN', 'IN-ST-10', 'Jharkhand', 'Pakur', '328', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D17']::text[], true),
  ('IN-D0246', 'IN', 'IN-ST-10', 'Jharkhand', 'Palamu', '329', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D18']::text[], true),
  ('IN-D0247', 'IN', 'IN-ST-10', 'Jharkhand', 'Ramgarh', '630', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D19']::text[], true),
  ('IN-D0248', 'IN', 'IN-ST-10', 'Jharkhand', 'Ranchi', '330', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D20']::text[], true),
  ('IN-D0249', 'IN', 'IN-ST-10', 'Jharkhand', 'Sahibganj', '331', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D21']::text[], true),
  ('IN-D0250', 'IN', 'IN-ST-10', 'Jharkhand', 'Saraikela Kharsawan', '609', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D22']::text[], true),
  ('IN-D0251', 'IN', 'IN-ST-10', 'Jharkhand', 'Simdega', '610', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D23']::text[], true),
  ('IN-D0252', 'IN', 'IN-ST-10', 'Jharkhand', 'West Singhbhum', '332', 'INDIA_CANONICAL_MASTER', ARRAY['JH-D24']::text[], true),
  ('IN-D0253', 'IN', 'IN-ST-11', 'Karnataka', 'Bagalkote', '524', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0254', 'IN', 'IN-ST-11', 'Karnataka', 'Ballari', '525', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0255', 'IN', 'IN-ST-11', 'Karnataka', 'Belagavi', '526', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0256', 'IN', 'IN-ST-11', 'Karnataka', 'Bengaluru Rural', '527', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0257', 'IN', 'IN-ST-11', 'Karnataka', 'Bengaluru Urban', '528', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0258', 'IN', 'IN-ST-11', 'Karnataka', 'Bidar', '529', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0259', 'IN', 'IN-ST-11', 'Karnataka', 'Chamarajanagara', '530', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0260', 'IN', 'IN-ST-11', 'Karnataka', 'Chikkaballapura', '631', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0261', 'IN', 'IN-ST-11', 'Karnataka', 'Chikkamagaluru', '531', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0262', 'IN', 'IN-ST-11', 'Karnataka', 'Chitradurga', '532', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0263', 'IN', 'IN-ST-11', 'Karnataka', 'Dakshina Kannada', '533', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0264', 'IN', 'IN-ST-11', 'Karnataka', 'Davanagere', '534', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0265', 'IN', 'IN-ST-11', 'Karnataka', 'Dharwad', '535', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0266', 'IN', 'IN-ST-11', 'Karnataka', 'Gadag', '536', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0267', 'IN', 'IN-ST-11', 'Karnataka', 'Hassan', '537', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0268', 'IN', 'IN-ST-11', 'Karnataka', 'Haveri', '538', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0269', 'IN', 'IN-ST-11', 'Karnataka', 'Kalaburagi', '539', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0270', 'IN', 'IN-ST-11', 'Karnataka', 'Kodagu', '540', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0271', 'IN', 'IN-ST-11', 'Karnataka', 'Kolar', '541', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0272', 'IN', 'IN-ST-11', 'Karnataka', 'Koppal', '542', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0273', 'IN', 'IN-ST-11', 'Karnataka', 'Mandya', '543', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0274', 'IN', 'IN-ST-11', 'Karnataka', 'Mysuru', '544', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0275', 'IN', 'IN-ST-11', 'Karnataka', 'Raichur', '545', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0276', 'IN', 'IN-ST-11', 'Karnataka', 'Ramanagara', '632', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0277', 'IN', 'IN-ST-11', 'Karnataka', 'Shivamogga', '546', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0278', 'IN', 'IN-ST-11', 'Karnataka', 'Tumakuru', '547', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0279', 'IN', 'IN-ST-11', 'Karnataka', 'Udupi', '548', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0280', 'IN', 'IN-ST-11', 'Karnataka', 'Uttara Kannada', '549', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0281', 'IN', 'IN-ST-11', 'Karnataka', 'Vijayanagara', '735', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0282', 'IN', 'IN-ST-11', 'Karnataka', 'Vijayapura', '550', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0283', 'IN', 'IN-ST-11', 'Karnataka', 'Yadgir', '639', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0284', 'IN', 'IN-ST-12', 'Kerala', 'Alappuzha', '560', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0285', 'IN', 'IN-ST-12', 'Kerala', 'Ernakulam', '561', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0286', 'IN', 'IN-ST-12', 'Kerala', 'Idukki', '562', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0287', 'IN', 'IN-ST-12', 'Kerala', 'Kannur', '563', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0288', 'IN', 'IN-ST-12', 'Kerala', 'Kasaragod', '564', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0289', 'IN', 'IN-ST-12', 'Kerala', 'Kollam', '565', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0290', 'IN', 'IN-ST-12', 'Kerala', 'Kottayam', '566', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0291', 'IN', 'IN-ST-12', 'Kerala', 'Kozhikode', '567', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0292', 'IN', 'IN-ST-12', 'Kerala', 'Malappuram', '568', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0293', 'IN', 'IN-ST-12', 'Kerala', 'Palakkad', '569', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0294', 'IN', 'IN-ST-12', 'Kerala', 'Pathanamthitta', '570', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0295', 'IN', 'IN-ST-12', 'Kerala', 'Thiruvananthapuram', '571', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0296', 'IN', 'IN-ST-12', 'Kerala', 'Thrissur', '572', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0297', 'IN', 'IN-ST-12', 'Kerala', 'Wayanad', '573', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0298', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Agar Malwa', '659', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0299', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Alirajpur', '634', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0300', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Anuppur', '389', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0301', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Ashoknagar', '390', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0302', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Balaghat', '391', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0303', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Barwani', '392', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0304', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Betul', '393', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0305', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Bhind', '394', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0306', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Bhopal', '395', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0307', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Burhanpur', '396', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0308', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Chhatarpur', '397', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0309', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Chhindwara', '398', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0310', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Damoh', '399', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0311', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Datia', '400', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0312', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Dewas', '401', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0313', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Dhar', '402', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0314', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Dindori', '403', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0315', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Guna', '404', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0316', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Gwalior', '405', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0317', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Harda', '406', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0318', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Hoshangabad', '407', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0319', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Indore', '408', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0320', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Jabalpur', '409', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0321', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Jhabua', '410', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0322', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Katni', '411', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0323', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Khandwa', '412', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0324', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Khargone', '413', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0325', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Maihar', '750', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0326', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Mandla', '414', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0327', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Mandsaur', '415', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0328', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Mauganj', '748', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0329', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Morena', '416', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0330', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Narsinghpur', '417', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0331', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Neemuch', '418', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0332', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Niwari', '724', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0333', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Pandhurna', '749', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0334', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Panna', '419', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0335', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Raisen', '420', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0336', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Rajgarh', '421', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0337', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Ratlam', '422', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0338', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Rewa', '423', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0339', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Sagar', '424', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0340', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Satna', '425', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0341', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Sehore', '426', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0342', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Seoni', '427', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0343', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Shahdol', '428', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0344', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Shajapur', '429', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0345', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Sheopur', '430', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0346', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Shivpuri', '431', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0347', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Sidhi', '432', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0348', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Singrauli', '635', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0349', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Tikamgarh', '433', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0350', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Ujjain', '434', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0351', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Umaria', '435', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0352', 'IN', 'IN-ST-13', 'Madhya Pradesh', 'Vidisha', '436', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0353', 'IN', 'IN-ST-14', 'Maharashtra', 'Ahmednagar', '463', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0354', 'IN', 'IN-ST-14', 'Maharashtra', 'Akola', '464', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0355', 'IN', 'IN-ST-14', 'Maharashtra', 'Amravati', '465', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0356', 'IN', 'IN-ST-14', 'Maharashtra', 'Beed', '467', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0357', 'IN', 'IN-ST-14', 'Maharashtra', 'Bhandara', '468', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0358', 'IN', 'IN-ST-14', 'Maharashtra', 'Buldhana', '469', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0359', 'IN', 'IN-ST-14', 'Maharashtra', 'Chandrapur', '470', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0360', 'IN', 'IN-ST-14', 'Maharashtra', 'Chhatrapati Sambhajinagar', '466', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0361', 'IN', 'IN-ST-14', 'Maharashtra', 'Dharashiv', '484', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0362', 'IN', 'IN-ST-14', 'Maharashtra', 'Dhule', '471', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0363', 'IN', 'IN-ST-14', 'Maharashtra', 'Gadchiroli', '472', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0364', 'IN', 'IN-ST-14', 'Maharashtra', 'Gondia', '473', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0365', 'IN', 'IN-ST-14', 'Maharashtra', 'Hingoli', '474', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0366', 'IN', 'IN-ST-14', 'Maharashtra', 'Jalgaon', '475', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0367', 'IN', 'IN-ST-14', 'Maharashtra', 'Jalna', '476', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0368', 'IN', 'IN-ST-14', 'Maharashtra', 'Kolhapur', '477', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0369', 'IN', 'IN-ST-14', 'Maharashtra', 'Latur', '478', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0370', 'IN', 'IN-ST-14', 'Maharashtra', 'Mumbai City', '479', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0371', 'IN', 'IN-ST-14', 'Maharashtra', 'Mumbai Suburban', '480', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0372', 'IN', 'IN-ST-14', 'Maharashtra', 'Nagpur', '481', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0373', 'IN', 'IN-ST-14', 'Maharashtra', 'Nanded', '482', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0374', 'IN', 'IN-ST-14', 'Maharashtra', 'Nandurbar', '483', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0375', 'IN', 'IN-ST-14', 'Maharashtra', 'Nashik', '485', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0376', 'IN', 'IN-ST-14', 'Maharashtra', 'Palghar', '666', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0377', 'IN', 'IN-ST-14', 'Maharashtra', 'Parbhani', '486', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0378', 'IN', 'IN-ST-14', 'Maharashtra', 'Pune', '487', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0379', 'IN', 'IN-ST-14', 'Maharashtra', 'Raigad', '488', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0380', 'IN', 'IN-ST-14', 'Maharashtra', 'Ratnagiri', '489', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0381', 'IN', 'IN-ST-14', 'Maharashtra', 'Sangli', '490', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0382', 'IN', 'IN-ST-14', 'Maharashtra', 'Satara', '491', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0383', 'IN', 'IN-ST-14', 'Maharashtra', 'Sindhudurg', '492', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0384', 'IN', 'IN-ST-14', 'Maharashtra', 'Solapur', '493', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0385', 'IN', 'IN-ST-14', 'Maharashtra', 'Thane', '494', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0386', 'IN', 'IN-ST-14', 'Maharashtra', 'Wardha', '495', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0387', 'IN', 'IN-ST-14', 'Maharashtra', 'Washim', '496', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0388', 'IN', 'IN-ST-14', 'Maharashtra', 'Yavatmal', '497', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0389', 'IN', 'IN-ST-15', 'Manipur', 'Bishnupur', '250', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0390', 'IN', 'IN-ST-15', 'Manipur', 'Chandel', '251', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0391', 'IN', 'IN-ST-15', 'Manipur', 'Churachandpur', '252', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0392', 'IN', 'IN-ST-15', 'Manipur', 'Imphal East', '253', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0393', 'IN', 'IN-ST-15', 'Manipur', 'Imphal West', '254', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0394', 'IN', 'IN-ST-15', 'Manipur', 'Jiribam', '684', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0395', 'IN', 'IN-ST-15', 'Manipur', 'Kakching', '685', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0396', 'IN', 'IN-ST-15', 'Manipur', 'Kamjong', '686', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0397', 'IN', 'IN-ST-15', 'Manipur', 'Kangpokpi', '687', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0398', 'IN', 'IN-ST-15', 'Manipur', 'Noney', '688', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0399', 'IN', 'IN-ST-15', 'Manipur', 'Pherzawl', '689', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0400', 'IN', 'IN-ST-15', 'Manipur', 'Senapati', '255', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0401', 'IN', 'IN-ST-15', 'Manipur', 'Tamenglong', '256', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0402', 'IN', 'IN-ST-15', 'Manipur', 'Tengnoupal', '690', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0403', 'IN', 'IN-ST-15', 'Manipur', 'Thoubal', '257', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0404', 'IN', 'IN-ST-15', 'Manipur', 'Ukhrul', '258', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0405', 'IN', 'IN-ST-16', 'Meghalaya', 'East Garo Hills', '273', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0406', 'IN', 'IN-ST-16', 'Meghalaya', 'East Jaintia Hills', '655', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0407', 'IN', 'IN-ST-16', 'Meghalaya', 'East Khasi Hills', '274', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0408', 'IN', 'IN-ST-16', 'Meghalaya', 'Eastern West Khasi Hills', '742', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0409', 'IN', 'IN-ST-16', 'Meghalaya', 'North Garo Hills', '656', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0410', 'IN', 'IN-ST-16', 'Meghalaya', 'Ri Bhoi', '275', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0411', 'IN', 'IN-ST-16', 'Meghalaya', 'South Garo Hills', '276', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0412', 'IN', 'IN-ST-16', 'Meghalaya', 'South West Garo Hills', '657', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0413', 'IN', 'IN-ST-16', 'Meghalaya', 'South West Khasi Hills', '658', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0414', 'IN', 'IN-ST-16', 'Meghalaya', 'West Garo Hills', '277', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0415', 'IN', 'IN-ST-16', 'Meghalaya', 'West Jaintia Hills', '278', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0416', 'IN', 'IN-ST-16', 'Meghalaya', 'West Khasi Hills', '279', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0417', 'IN', 'IN-ST-17', 'Mizoram', 'Aizawl', '259', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0418', 'IN', 'IN-ST-17', 'Mizoram', 'Champhai', '260', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0419', 'IN', 'IN-ST-17', 'Mizoram', 'Hnahthial', '725', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0420', 'IN', 'IN-ST-17', 'Mizoram', 'Khawzawl', '726', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0421', 'IN', 'IN-ST-17', 'Mizoram', 'Kolasib', '261', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0422', 'IN', 'IN-ST-17', 'Mizoram', 'Lawngtlai', '262', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0423', 'IN', 'IN-ST-17', 'Mizoram', 'Lunglei', '263', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0424', 'IN', 'IN-ST-17', 'Mizoram', 'Mamit', '264', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0425', 'IN', 'IN-ST-17', 'Mizoram', 'Saitual', '727', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0426', 'IN', 'IN-ST-17', 'Mizoram', 'Serchhip', '265', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0427', 'IN', 'IN-ST-17', 'Mizoram', 'Siaha', '266', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0428', 'IN', 'IN-ST-18', 'Nagaland', 'Chümoukedima', '737', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0429', 'IN', 'IN-ST-18', 'Nagaland', 'Dimapur', '267', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0430', 'IN', 'IN-ST-18', 'Nagaland', 'Kiphire', '612', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0431', 'IN', 'IN-ST-18', 'Nagaland', 'Kohima', '268', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0432', 'IN', 'IN-ST-18', 'Nagaland', 'Longleng', '613', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0433', 'IN', 'IN-ST-18', 'Nagaland', 'Mokokchung', '269', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0434', 'IN', 'IN-ST-18', 'Nagaland', 'Mon', '270', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0435', 'IN', 'IN-ST-18', 'Nagaland', 'Niuland', '738', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0436', 'IN', 'IN-ST-18', 'Nagaland', 'Noklak', '730', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0437', 'IN', 'IN-ST-18', 'Nagaland', 'Peren', '614', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0438', 'IN', 'IN-ST-18', 'Nagaland', 'Phek', '271', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0439', 'IN', 'IN-ST-18', 'Nagaland', 'Shamator', '739', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0440', 'IN', 'IN-ST-18', 'Nagaland', 'Tseminyü', '741', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0441', 'IN', 'IN-ST-18', 'Nagaland', 'Tuensang', '272', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0442', 'IN', 'IN-ST-18', 'Nagaland', 'Wokha', '273', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0443', 'IN', 'IN-ST-18', 'Nagaland', 'Zünheboto', '274', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0444', 'IN', 'IN-ST-19', 'Odisha', 'Angul', '347', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0445', 'IN', 'IN-ST-19', 'Odisha', 'Balangir', '348', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0446', 'IN', 'IN-ST-19', 'Odisha', 'Balasore', '349', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0447', 'IN', 'IN-ST-19', 'Odisha', 'Bargarh', '350', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0448', 'IN', 'IN-ST-19', 'Odisha', 'Bhadrak', '351', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0449', 'IN', 'IN-ST-19', 'Odisha', 'Boudh', '352', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0450', 'IN', 'IN-ST-19', 'Odisha', 'Cuttack', '353', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0451', 'IN', 'IN-ST-19', 'Odisha', 'Deogarh', '354', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0452', 'IN', 'IN-ST-19', 'Odisha', 'Dhenkanal', '355', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0453', 'IN', 'IN-ST-19', 'Odisha', 'Gajapati', '356', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0454', 'IN', 'IN-ST-19', 'Odisha', 'Ganjam', '357', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0455', 'IN', 'IN-ST-19', 'Odisha', 'Jagatsinghpur', '358', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0456', 'IN', 'IN-ST-19', 'Odisha', 'Jajpur', '359', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0457', 'IN', 'IN-ST-19', 'Odisha', 'Jharsuguda', '360', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0458', 'IN', 'IN-ST-19', 'Odisha', 'Kalahandi', '361', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0459', 'IN', 'IN-ST-19', 'Odisha', 'Kandhamal', '362', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0460', 'IN', 'IN-ST-19', 'Odisha', 'Kendrapara', '363', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0461', 'IN', 'IN-ST-19', 'Odisha', 'Kendujhar', '364', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0462', 'IN', 'IN-ST-19', 'Odisha', 'Khordha', '365', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0463', 'IN', 'IN-ST-19', 'Odisha', 'Koraput', '366', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0464', 'IN', 'IN-ST-19', 'Odisha', 'Malkangiri', '367', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0465', 'IN', 'IN-ST-19', 'Odisha', 'Mayurbhanj', '368', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0466', 'IN', 'IN-ST-19', 'Odisha', 'Nabarangpur', '369', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0467', 'IN', 'IN-ST-19', 'Odisha', 'Nayagarh', '370', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0468', 'IN', 'IN-ST-19', 'Odisha', 'Nuapada', '371', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0469', 'IN', 'IN-ST-19', 'Odisha', 'Puri', '372', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0470', 'IN', 'IN-ST-19', 'Odisha', 'Rayagada', '373', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0471', 'IN', 'IN-ST-19', 'Odisha', 'Sambalpur', '374', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0472', 'IN', 'IN-ST-19', 'Odisha', 'Subarnapur', '375', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0473', 'IN', 'IN-ST-19', 'Odisha', 'Sundargarh', '376', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0474', 'IN', 'IN-ST-20', 'Punjab', 'Amritsar', '28', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0475', 'IN', 'IN-ST-20', 'Punjab', 'Barnala', '615', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0476', 'IN', 'IN-ST-20', 'Punjab', 'Bathinda', '29', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0477', 'IN', 'IN-ST-20', 'Punjab', 'Faridkot', '30', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0478', 'IN', 'IN-ST-20', 'Punjab', 'Fatehgarh Sahib', '31', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0479', 'IN', 'IN-ST-20', 'Punjab', 'Fazilka', '650', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0480', 'IN', 'IN-ST-20', 'Punjab', 'Ferozepur', '32', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0481', 'IN', 'IN-ST-20', 'Punjab', 'Gurdaspur', '33', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0482', 'IN', 'IN-ST-20', 'Punjab', 'Hoshiarpur', '34', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0483', 'IN', 'IN-ST-20', 'Punjab', 'Jalandhar', '35', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0484', 'IN', 'IN-ST-20', 'Punjab', 'Kapurthala', '36', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0485', 'IN', 'IN-ST-20', 'Punjab', 'Ludhiana', '37', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0486', 'IN', 'IN-ST-20', 'Punjab', 'Malerkotla', '733', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0487', 'IN', 'IN-ST-20', 'Punjab', 'Mansa', '38', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0488', 'IN', 'IN-ST-20', 'Punjab', 'Moga', '39', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0489', 'IN', 'IN-ST-20', 'Punjab', 'Pathankot', '651', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0490', 'IN', 'IN-ST-20', 'Punjab', 'Patiala', '40', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0491', 'IN', 'IN-ST-20', 'Punjab', 'Rupnagar', '41', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0492', 'IN', 'IN-ST-20', 'Punjab', 'Sahibzada Ajit Singh Nagar', '616', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0493', 'IN', 'IN-ST-20', 'Punjab', 'Shahid Bhagat Singh Nagar', '42', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0494', 'IN', 'IN-ST-20', 'Punjab', 'Sri Muktsar Sahib', '43', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0495', 'IN', 'IN-ST-20', 'Punjab', 'Tarn Taran', '617', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0496', 'IN', 'IN-ST-21', 'Rajasthan', 'Ajmer', '86', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0497', 'IN', 'IN-ST-21', 'Rajasthan', 'Alwar', '87', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0498', 'IN', 'IN-ST-21', 'Rajasthan', 'Anupgarh', '751', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0499', 'IN', 'IN-ST-21', 'Rajasthan', 'Balotra', '752', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0500', 'IN', 'IN-ST-21', 'Rajasthan', 'Banswara', '88', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0501', 'IN', 'IN-ST-21', 'Rajasthan', 'Baran', '89', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0502', 'IN', 'IN-ST-21', 'Rajasthan', 'Barmer', '90', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0503', 'IN', 'IN-ST-21', 'Rajasthan', 'Beawar', '753', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0504', 'IN', 'IN-ST-21', 'Rajasthan', 'Bharatpur', '91', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0505', 'IN', 'IN-ST-21', 'Rajasthan', 'Bhilwara', '92', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0506', 'IN', 'IN-ST-21', 'Rajasthan', 'Bikaner', '93', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0507', 'IN', 'IN-ST-21', 'Rajasthan', 'Bundi', '94', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0508', 'IN', 'IN-ST-21', 'Rajasthan', 'Chittorgarh', '95', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0509', 'IN', 'IN-ST-21', 'Rajasthan', 'Churu', '96', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0510', 'IN', 'IN-ST-21', 'Rajasthan', 'Dausa', '97', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0511', 'IN', 'IN-ST-21', 'Rajasthan', 'Deeg', '754', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0512', 'IN', 'IN-ST-21', 'Rajasthan', 'Dholpur', '98', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0513', 'IN', 'IN-ST-21', 'Rajasthan', 'Didwana-Kuchaman', '755', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0514', 'IN', 'IN-ST-21', 'Rajasthan', 'Dudu', '756', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0515', 'IN', 'IN-ST-21', 'Rajasthan', 'Dungarpur', '99', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0516', 'IN', 'IN-ST-21', 'Rajasthan', 'Ganganagar', '100', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0517', 'IN', 'IN-ST-21', 'Rajasthan', 'Gangapur City', '757', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0518', 'IN', 'IN-ST-21', 'Rajasthan', 'Hanumangarh', '101', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0519', 'IN', 'IN-ST-21', 'Rajasthan', 'Jaipur', '102', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0520', 'IN', 'IN-ST-21', 'Rajasthan', 'Jaipur Rural', '758', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0521', 'IN', 'IN-ST-21', 'Rajasthan', 'Jaisalmer', '103', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0522', 'IN', 'IN-ST-21', 'Rajasthan', 'Jalore', '104', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0523', 'IN', 'IN-ST-21', 'Rajasthan', 'Jhalawar', '105', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0524', 'IN', 'IN-ST-21', 'Rajasthan', 'Jhunjhunu', '106', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0525', 'IN', 'IN-ST-21', 'Rajasthan', 'Jodhpur', '107', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0526', 'IN', 'IN-ST-21', 'Rajasthan', 'Jodhpur Rural', '759', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0527', 'IN', 'IN-ST-21', 'Rajasthan', 'Karauli', '108', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0528', 'IN', 'IN-ST-21', 'Rajasthan', 'Kekri', '760', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0529', 'IN', 'IN-ST-21', 'Rajasthan', 'Khairthal-Tijara', '761', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0530', 'IN', 'IN-ST-21', 'Rajasthan', 'Kota', '109', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0531', 'IN', 'IN-ST-21', 'Rajasthan', 'Kotputli-Behror', '762', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0532', 'IN', 'IN-ST-21', 'Rajasthan', 'Nagaur', '110', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0533', 'IN', 'IN-ST-21', 'Rajasthan', 'Neem Ka Thana', '763', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0534', 'IN', 'IN-ST-21', 'Rajasthan', 'Pali', '111', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0535', 'IN', 'IN-ST-21', 'Rajasthan', 'Phalodi', '764', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0536', 'IN', 'IN-ST-21', 'Rajasthan', 'Pratapgarh', '633', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0537', 'IN', 'IN-ST-21', 'Rajasthan', 'Rajsamand', '112', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0538', 'IN', 'IN-ST-21', 'Rajasthan', 'Salumber', '765', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0539', 'IN', 'IN-ST-21', 'Rajasthan', 'Sanchore', '766', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0540', 'IN', 'IN-ST-21', 'Rajasthan', 'Sawai Madhopur', '113', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0541', 'IN', 'IN-ST-21', 'Rajasthan', 'Shahpura', '767', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0542', 'IN', 'IN-ST-21', 'Rajasthan', 'Sikar', '114', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0543', 'IN', 'IN-ST-21', 'Rajasthan', 'Sirohi', '115', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0544', 'IN', 'IN-ST-21', 'Rajasthan', 'Tonk', '116', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0545', 'IN', 'IN-ST-21', 'Rajasthan', 'Udaipur', '117', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0546', 'IN', 'IN-ST-22', 'Sikkim', 'Gangtok', '225', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0547', 'IN', 'IN-ST-22', 'Sikkim', 'Gyalshing', '226', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0548', 'IN', 'IN-ST-22', 'Sikkim', 'Mangan', '227', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0549', 'IN', 'IN-ST-22', 'Sikkim', 'Namchi', '228', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0550', 'IN', 'IN-ST-22', 'Sikkim', 'Pakyong', '731', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0551', 'IN', 'IN-ST-22', 'Sikkim', 'Soreng', '732', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0552', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Ariyalur', '632', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0553', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Chengalpattu', '728', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0554', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Chennai', '574', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0555', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Coimbatore', '575', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0556', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Cuddalore', '576', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0557', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Dharmapuri', '577', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0558', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Dindigul', '578', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0559', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Erode', '579', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0560', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Kallakurichi', '729', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0561', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Kanchipuram', '580', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0562', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Kanyakumari', '581', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0563', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Karur', '582', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0564', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Krishnagiri', '600', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0565', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Madurai', '583', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0566', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Mayiladuthurai', '733', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0567', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Nagapattinam', '584', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0568', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Namakkal', '585', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0569', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Nilgiris', '586', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0570', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Perambalur', '587', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0571', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Pudukkottai', '588', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0572', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Ramanathapuram', '589', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0573', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Ranipet', '734', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0574', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Salem', '590', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0575', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Sivaganga', '591', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0576', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Tenkasi', '735', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0577', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Thanjavur', '592', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0578', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Theni', '593', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0579', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Thoothukudi', '594', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0580', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Tiruchirappalli', '595', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0581', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Tirunelveli', '596', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0582', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Tirupathur', '736', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0583', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Tiruppur', '633', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0584', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Tiruvallur', '597', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0585', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Tiruvannamalai', '598', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0586', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Tiruvarur', '599', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0587', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Vellore', '601', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0588', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Viluppuram', '602', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0589', 'IN', 'IN-ST-23', 'Tamil Nadu', 'Virudhunagar', '603', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0590', 'IN', 'IN-ST-24', 'Telangana', 'Adilabad', '501', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0591', 'IN', 'IN-ST-24', 'Telangana', 'Bhadradri Kothagudem', '691', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0592', 'IN', 'IN-ST-24', 'Telangana', 'Hanamkonda', '692', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0593', 'IN', 'IN-ST-24', 'Telangana', 'Hyderabad', '507', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0594', 'IN', 'IN-ST-24', 'Telangana', 'Jagtial', '693', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0595', 'IN', 'IN-ST-24', 'Telangana', 'Jangaon', '694', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0596', 'IN', 'IN-ST-24', 'Telangana', 'Jayashankar Bhupalpally', '695', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0597', 'IN', 'IN-ST-24', 'Telangana', 'Jogulamba Gadwal', '696', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0598', 'IN', 'IN-ST-24', 'Telangana', 'Kamareddy', '697', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0599', 'IN', 'IN-ST-24', 'Telangana', 'Karimnagar', '508', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0600', 'IN', 'IN-ST-24', 'Telangana', 'Khammam', '509', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0601', 'IN', 'IN-ST-24', 'Telangana', 'Kumuram Bheem Asifabad', '698', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0602', 'IN', 'IN-ST-24', 'Telangana', 'Mahabubabad', '699', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0603', 'IN', 'IN-ST-24', 'Telangana', 'Mahabubnagar', '512', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0604', 'IN', 'IN-ST-24', 'Telangana', 'Mancherial', '700', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0605', 'IN', 'IN-ST-24', 'Telangana', 'Medak', '513', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0606', 'IN', 'IN-ST-24', 'Telangana', 'Medchal-Malkajgiri', '701', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0607', 'IN', 'IN-ST-24', 'Telangana', 'Mulugu', '737', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0608', 'IN', 'IN-ST-24', 'Telangana', 'Nagarkurnool', '702', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0609', 'IN', 'IN-ST-24', 'Telangana', 'Nalgonda', '514', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0610', 'IN', 'IN-ST-24', 'Telangana', 'Narayanpet', '738', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0611', 'IN', 'IN-ST-24', 'Telangana', 'Nirmal', '703', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0612', 'IN', 'IN-ST-24', 'Telangana', 'Nizamabad', '516', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0613', 'IN', 'IN-ST-24', 'Telangana', 'Peddapalli', '704', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0614', 'IN', 'IN-ST-24', 'Telangana', 'Rajanna Sircilla', '705', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0615', 'IN', 'IN-ST-24', 'Telangana', 'Rangareddy', '518', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0616', 'IN', 'IN-ST-24', 'Telangana', 'Sangareddy', '706', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0617', 'IN', 'IN-ST-24', 'Telangana', 'Siddipet', '707', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0618', 'IN', 'IN-ST-24', 'Telangana', 'Suryapet', '708', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0619', 'IN', 'IN-ST-24', 'Telangana', 'Vikarabad', '709', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0620', 'IN', 'IN-ST-24', 'Telangana', 'Wanaparthy', '710', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0621', 'IN', 'IN-ST-24', 'Telangana', 'Warangal', '522', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0622', 'IN', 'IN-ST-24', 'Telangana', 'Yadadri Bhuvanagiri', '711', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0623', 'IN', 'IN-ST-25', 'Tripura', 'Dhalai', '280', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0624', 'IN', 'IN-ST-25', 'Tripura', 'Gomati', '658', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0625', 'IN', 'IN-ST-25', 'Tripura', 'Khowai', '659', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0626', 'IN', 'IN-ST-25', 'Tripura', 'North Tripura', '281', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0627', 'IN', 'IN-ST-25', 'Tripura', 'Sepahijala', '660', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0628', 'IN', 'IN-ST-25', 'Tripura', 'South Tripura', '282', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0629', 'IN', 'IN-ST-25', 'Tripura', 'Unakoti', '661', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0630', 'IN', 'IN-ST-25', 'Tripura', 'West Tripura', '283', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0631', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Agra', '138', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0632', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Aligarh', '139', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0633', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Ambedkar Nagar', '140', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0634', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Amethi', '652', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0635', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Amroha', '154', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0636', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Auraiya', '141', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0637', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Ayodhya', '150', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0638', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Azamgarh', '142', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0639', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Baghpat', '143', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0640', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Bahraich', '144', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0641', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Ballia', '145', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0642', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Balrampur', '146', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0643', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Banda', '147', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0644', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Barabanki', '148', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0645', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Bareilly', '149', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0646', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Basti', '151', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0647', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Bhadohi', '185', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0648', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Bijnor', '152', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0649', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Budaun', '153', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0650', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Bulandshahr', '155', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0651', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Chandauli', '156', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0652', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Chitrakoot', '157', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0653', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Deoria', '158', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0654', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Etah', '159', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0655', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Etawah', '160', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0656', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Farrukhabad', '161', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0657', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Fatehpur', '162', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0658', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Firozabad', '163', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0659', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Gautam Buddha Nagar', '164', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0660', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Ghaziabad', '165', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0661', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Ghazipur', '166', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0662', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Gonda', '167', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0663', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Gorakhpur', '168', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0664', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Hamirpur', '169', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0665', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Hapur', '653', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0666', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Hardoi', '170', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0667', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Hathras', '171', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0668', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Jalaun', '172', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0669', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Jaunpur', '173', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0670', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Jhansi', '174', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0671', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Kannauj', '175', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0672', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Kanpur Dehat', '176', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0673', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Kanpur Nagar', '177', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0674', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Kasganj', '635', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0675', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Kaushambi', '178', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0676', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Kheri', '179', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0677', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Kushinagar', '180', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0678', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Lalitpur', '181', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0679', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Lucknow', '182', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0680', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Maharajganj', '183', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0681', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Mahoba', '184', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0682', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Mainpuri', '186', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0683', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Mathura', '187', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0684', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Mau', '188', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0685', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Meerut', '189', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0686', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Mirzapur', '190', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0687', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Moradabad', '191', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0688', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Muzaffarnagar', '192', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0689', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Pilibhit', '193', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0690', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Pratapgarh', '194', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0691', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Prayagraj', '137', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0692', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Raebareli', '195', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0693', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Rampur', '196', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0694', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Saharanpur', '197', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0695', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Sambhal', '654', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0696', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Sant Kabir Nagar', '198', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0697', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Shahjahanpur', '199', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0698', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Shamli', '655', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0699', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Shrawasti', '200', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0700', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Siddharthnagar', '201', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0701', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Sitapur', '202', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0702', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Sonbhadra', '203', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0703', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Sultanpur', '204', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0704', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Unnao', '205', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0705', 'IN', 'IN-ST-26', 'Uttar Pradesh', 'Varanasi', '206', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0706', 'IN', 'IN-ST-27', 'Uttarakhand', 'Almora', '44', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0707', 'IN', 'IN-ST-27', 'Uttarakhand', 'Bageshwar', '45', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0708', 'IN', 'IN-ST-27', 'Uttarakhand', 'Chamoli', '46', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0709', 'IN', 'IN-ST-27', 'Uttarakhand', 'Champawat', '47', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0710', 'IN', 'IN-ST-27', 'Uttarakhand', 'Dehradun', '48', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0711', 'IN', 'IN-ST-27', 'Uttarakhand', 'Haridwar', '49', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0712', 'IN', 'IN-ST-27', 'Uttarakhand', 'Nainital', '50', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0713', 'IN', 'IN-ST-27', 'Uttarakhand', 'Pauri Garhwal', '51', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0714', 'IN', 'IN-ST-27', 'Uttarakhand', 'Pithoragarh', '52', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0715', 'IN', 'IN-ST-27', 'Uttarakhand', 'Rudraprayag', '53', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0716', 'IN', 'IN-ST-27', 'Uttarakhand', 'Tehri Garhwal', '54', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0717', 'IN', 'IN-ST-27', 'Uttarakhand', 'Udham Singh Nagar', '55', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0718', 'IN', 'IN-ST-27', 'Uttarakhand', 'Uttarkashi', '56', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0719', 'IN', 'IN-ST-28', 'West Bengal', 'Alipurduar', '668', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0720', 'IN', 'IN-ST-28', 'West Bengal', 'Bankura', '310', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0721', 'IN', 'IN-ST-28', 'West Bengal', 'Birbhum', '311', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0722', 'IN', 'IN-ST-28', 'West Bengal', 'Cooch Behar', '312', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0723', 'IN', 'IN-ST-28', 'West Bengal', 'Dakshin Dinajpur', '313', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0724', 'IN', 'IN-ST-28', 'West Bengal', 'Darjeeling', '314', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0725', 'IN', 'IN-ST-28', 'West Bengal', 'Hooghly', '315', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0726', 'IN', 'IN-ST-28', 'West Bengal', 'Howrah', '316', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0727', 'IN', 'IN-ST-28', 'West Bengal', 'Jalpaiguri', '317', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0728', 'IN', 'IN-ST-28', 'West Bengal', 'Jhargram', '707', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0729', 'IN', 'IN-ST-28', 'West Bengal', 'Kalimpong', '708', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0730', 'IN', 'IN-ST-28', 'West Bengal', 'Kolkata', '318', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0731', 'IN', 'IN-ST-28', 'West Bengal', 'Malda', '319', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0732', 'IN', 'IN-ST-28', 'West Bengal', 'Murshidabad', '320', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0733', 'IN', 'IN-ST-28', 'West Bengal', 'Nadia', '321', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0734', 'IN', 'IN-ST-28', 'West Bengal', 'North 24 Parganas', '322', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0735', 'IN', 'IN-ST-28', 'West Bengal', 'Paschim Bardhaman', '709', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0736', 'IN', 'IN-ST-28', 'West Bengal', 'Paschim Medinipur', '323', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0737', 'IN', 'IN-ST-28', 'West Bengal', 'Purba Bardhaman', '710', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0738', 'IN', 'IN-ST-28', 'West Bengal', 'Purba Medinipur', '324', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0739', 'IN', 'IN-ST-28', 'West Bengal', 'Purulia', '325', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0740', 'IN', 'IN-ST-28', 'West Bengal', 'South 24 Parganas', '326', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0741', 'IN', 'IN-ST-28', 'West Bengal', 'Uttar Dinajpur', '327', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0742', 'IN', 'IN-ST-29', 'Andaman and Nicobar Islands', 'Nicobar', '601', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0743', 'IN', 'IN-ST-29', 'Andaman and Nicobar Islands', 'North and Middle Andaman', '632', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0744', 'IN', 'IN-ST-29', 'Andaman and Nicobar Islands', 'South Andaman', '603', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0745', 'IN', 'IN-ST-30', 'Chandigarh', 'Chandigarh', '43', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0746', 'IN', 'IN-ST-31', 'Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli', '464', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0747', 'IN', 'IN-ST-31', 'Dadra and Nagar Haveli and Daman and Diu', 'Daman', '465', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0748', 'IN', 'IN-ST-31', 'Dadra and Nagar Haveli and Daman and Diu', 'Diu', '466', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0749', 'IN', 'IN-ST-32', 'Delhi', 'Central Delhi', '76', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0750', 'IN', 'IN-ST-32', 'Delhi', 'East Delhi', '77', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0751', 'IN', 'IN-ST-32', 'Delhi', 'New Delhi', '78', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0752', 'IN', 'IN-ST-32', 'Delhi', 'North Delhi', '79', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0753', 'IN', 'IN-ST-32', 'Delhi', 'North East Delhi', '80', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0754', 'IN', 'IN-ST-32', 'Delhi', 'North West Delhi', '81', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0755', 'IN', 'IN-ST-32', 'Delhi', 'Shahdara', '662', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0756', 'IN', 'IN-ST-32', 'Delhi', 'South Delhi', '82', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0757', 'IN', 'IN-ST-32', 'Delhi', 'South East Delhi', '663', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0758', 'IN', 'IN-ST-32', 'Delhi', 'South West Delhi', '83', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0759', 'IN', 'IN-ST-32', 'Delhi', 'West Delhi', '84', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0760', 'IN', 'IN-ST-33', 'Jammu and Kashmir', 'Anantnag', '1', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0761', 'IN', 'IN-ST-33', 'Jammu and Kashmir', 'Bandipora', '620', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0762', 'IN', 'IN-ST-33', 'Jammu and Kashmir', 'Baramulla', '2', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0763', 'IN', 'IN-ST-33', 'Jammu and Kashmir', 'Budgam', '3', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0764', 'IN', 'IN-ST-33', 'Jammu and Kashmir', 'Doda', '4', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0765', 'IN', 'IN-ST-33', 'Jammu and Kashmir', 'Ganderbal', '621', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0766', 'IN', 'IN-ST-33', 'Jammu and Kashmir', 'Jammu', '5', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0767', 'IN', 'IN-ST-33', 'Jammu and Kashmir', 'Kathua', '6', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0768', 'IN', 'IN-ST-33', 'Jammu and Kashmir', 'Kishtwar', '622', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0769', 'IN', 'IN-ST-33', 'Jammu and Kashmir', 'Kulgam', '623', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0770', 'IN', 'IN-ST-33', 'Jammu and Kashmir', 'Kupwara', '7', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0771', 'IN', 'IN-ST-33', 'Jammu and Kashmir', 'Poonch', '8', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0772', 'IN', 'IN-ST-33', 'Jammu and Kashmir', 'Pulwama', '9', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0773', 'IN', 'IN-ST-33', 'Jammu and Kashmir', 'Rajouri', '10', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0774', 'IN', 'IN-ST-33', 'Jammu and Kashmir', 'Ramban', '624', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0775', 'IN', 'IN-ST-33', 'Jammu and Kashmir', 'Reasi', '625', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0776', 'IN', 'IN-ST-33', 'Jammu and Kashmir', 'Samba', '626', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0777', 'IN', 'IN-ST-33', 'Jammu and Kashmir', 'Shopian', '627', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0778', 'IN', 'IN-ST-33', 'Jammu and Kashmir', 'Srinagar', '11', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0779', 'IN', 'IN-ST-33', 'Jammu and Kashmir', 'Udhampur', '12', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0780', 'IN', 'IN-ST-34', 'Ladakh', 'Kargil', '13', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0781', 'IN', 'IN-ST-34', 'Ladakh', 'Leh', '14', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0782', 'IN', 'IN-ST-35', 'Lakshadweep', 'Lakshadweep', '553', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0783', 'IN', 'IN-ST-36', 'Puducherry', 'Karaikal', '604', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0784', 'IN', 'IN-ST-36', 'Puducherry', 'Mahe', '605', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0785', 'IN', 'IN-ST-36', 'Puducherry', 'Puducherry', '606', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true),
  ('IN-D0786', 'IN', 'IN-ST-36', 'Puducherry', 'Yanam', '607', 'INDIA_CANONICAL_MASTER', ARRAY[]::text[], true)
ON CONFLICT (id) DO UPDATE SET
  state_code = EXCLUDED.state_code,
  state_name = EXCLUDED.state_name,
  district_name = EXCLUDED.district_name,
  official_district_code = EXCLUDED.official_district_code,
  canonical_source = EXCLUDED.canonical_source,
  alternate_source_codes = EXCLUDED.alternate_source_codes,
  is_active = true,
  updated_at = now();

ANALYZE public.districts;
